// AUTO-GENERATED catalogue additions — derived from resources/LumenxProductList.csv and the
// datasheet payloads in server/datasheets-data (see resources/catalogue-progress.md).
import { Product, ProductCategory } from './types';

export const NEW_CATEGORIES: ProductCategory[] = [
  {
    id: "decorative",
    title: "Decorative",
    description: "Statement chandeliers and decorative series that make interiors feel curated — layered acrylic, crystal and sculptural forms.",
    applications: "Hotels, restaurants, residences and feature interiors",
    imageUrl: "/product-images/categories/decorative.jpg",
    linkLabel: "Explore Decorative",
  },
  {
    id: "indoor-architectural",
    title: "Architectural — Indoor",
    description: "Recessed, surface and suspended architectural luminaires for refined interior detailing — circular systems, pendants and ceiling lights.",
    applications: "Offices, hospitality, retail and residential architecture",
    imageUrl: "/product-images/categories/indoor-architectural.jpg",
    linkLabel: "Explore Architectural — Indoor",
  },
  {
    id: "outdoor-architectural",
    title: "Architectural — Outdoor",
    description: "Outdoor spots, bollards, post-tops, wall lights and in-ground luminaires for considered exterior architecture and landscape.",
    applications: "Facades, gardens, pathways, plazas and streetscapes",
    imageUrl: "/product-images/categories/outdoor-architectural.jpg",
    linkLabel: "Explore Architectural — Outdoor",
  },
  {
    id: "sensors",
    title: "Sensors",
    description: "Motion and presence detectors for indoor and outdoor automation — PIR, HF and ultrasonic with adjustable detection zones.",
    applications: "Offices, warehouses, corridors, parking and security",
    imageUrl: "/product-images/categories/sensors.jpg",
    linkLabel: "Explore Sensors",
  },
  {
    id: "solar",
    title: "Solar",
    description: "All-in-one solar post-top and area lighting for sites with no grid — self-sustaining with integrated panels and batteries.",
    applications: "Estates, parks, isolated streets and gate posts",
    imageUrl: "/product-images/categories/solar.svg",
    linkLabel: "Explore Solar",
  },
  {
    id: "profiles",
    title: "Profiles & Accessories",
    description: "Extrusion profiles and system accessories for integrating LED tape into architecture and millwork.",
    applications: "Coves, joinery, display and linear detailing",
    imageUrl: "/product-images/categories/profiles.jpg",
    linkLabel: "Explore Profiles & Accessories",
  },
];

export const NEW_PRODUCTS: Product[] = [
  {
    slug: "profiles",
    name: "Profiles",
    category: "profiles",
    supplier: "LBY",
    summary: "Profiles — Profiles supplied by LumenX.",
    description: "Profiles — Profiles supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Coves","Joinery","Display","Millwork"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "sunfor-solar-range",
    name: "Sunfor",
    category: "solar",
    supplier: "Sunfor",
    summary: "Sunfor — supplied by LumenX.",
    description: "Sunfor — supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Estates","Parks","Isolated sites","Security"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "sky-ele-15-solar-post-top",
    name: "Sky ELE-15 Solar Post Top",
    category: "solar",
    supplier: "Superlume",
    summary: "All-in-one solar-powered LED post top fitting for areas with no electrical infrastructure — fully integrated battery, zero wirin…",
    description: "All-in-one solar-powered LED post top fitting for areas with no electrical infrastructure — fully integrated battery, zero wiring and minimal maintenance. Ideal for estates, public parks, isolated streets and gate posts.",
    specs: [
      { label: "Nominal Flux", value: "Up to 2000 lm" },
      { label: "Efficacy", value: "Up to 100 lm/W" },
      { label: "Colour Temperature", value: "6000K" },
      { label: "Recommended Mounting Height", value: "4-5 m" },
      { label: "Storage Capacity", value: "86.58 Wh lithium battery, 3.7V, 10400 mAh" },
      { label: "Autonomy", value: ">24 h at full charge · up to 3 rainy days" },
      { label: "Charging Time", value: "7-8 h" },
      { label: "Lifespan", value: ">4000 cycles @ 80% DoD · 10-year lifetime" },
      { label: "IP Rating", value: "IP65" },
      { label: "Solar Panel", value: "6 W / 6 V high-efficiency panel (18%)" },
      { label: "Product Size (L × W × H)", value: "500 × 500 × 200mm" },
    ],
    features: [],
    applications: ["Estates","Public parks","Isolated streets","Gate posts"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/sky-ele-15-solar-post-top",
  },
  {
    slug: "sky-spt-150-solar-post-top",
    name: "Sky SPT-150 Solar Post Top",
    category: "solar",
    supplier: "Superlume",
    summary: "Self-sustaining solar-powered post top light delivering reliable performance for estates, isolated areas and security perimeters…",
    description: "Self-sustaining solar-powered post top light delivering reliable performance for estates, isolated areas and security perimeters — no electrical connection required.",
    specs: [
      { label: "Nominal Flux", value: "Up to 1100 lm" },
      { label: "Colour Temperature", value: "6000K" },
      { label: "Storage Capacity", value: "3.2V / 15000 mAh" },
      { label: "Charging Time", value: "7-8 h" },
      { label: "IP Rating", value: "IP65" },
      { label: "Solar Panel", value: "6V / 15W" },
      { label: "Product Size (L × W × H)", value: "420 × 420 × 130mm" },
    ],
    features: [],
    applications: ["Estates","Isolated areas","Security perimeters"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/sky-spt-150-solar-post-top",
  },
  {
    slug: "pioled",
    name: "Pioled",
    category: "solar",
    supplier: "Pioled",
    summary: "Pioled — supplied by LumenX.",
    description: "Pioled — supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Estates","Parks","Isolated sites","Security"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "steinel-is-2360-r",
    name: "IS 2360 R",
    category: "sensors",
    supplier: "Steinel",
    summary: "STEINEL inside. Intelligent technology for installation. The perfect infrared sensor for installing in projecting roofs and susp…",
    description: "STEINEL inside. Intelligent technology for installation. The perfect infrared sensor for installing in projecting roofs and suspended ceilings. The IS 2360 DE ECO has a reach of up to 8 m in diameter and an impressive 360° angle of coverage. The detection zone can be adjusted where necessary by using shrouds.",
    specs: [
      { label: "Application, place", value: "Outdoors, Indoors" },
      { label: "Installation", value: "In-ceiling installation" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "Ø 8 m (50 m²)" },
      { label: "Mounting height max.", value: "4,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "white" },
      { label: "PU1, net weight", value: "0,117 kg" },
      { label: "infrared sensor 360°", value: "max. 4 m" },
      { label: "1000 W max.", value: "IP54" },
      { label: "2 - 2000 lux", value: "8 sec - 35 min" },
      { label: "manufacturer's warranty steinel.de/garantie", value: "CE" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-is-2360-r.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-is-2360-r",
  },
  {
    slug: "steinel-is-2360-s",
    name: "IS 2360 S",
    category: "sensors",
    supplier: "Steinel",
    summary: "Slips into the background. And detects every movement. Stylish infrared ceiling sensor with an unobtrusive compact look. The sur…",
    description: "Slips into the background. And detects every movement. Stylish infrared ceiling sensor with an unobtrusive compact look. The surface-mounted IS 2360 motion detector with passive infrared sensor technology is the perfect choice for porches and small rooms. With a reach of 7 m and 360° detection zone, it reliably detects all movements with absolute precision. The precision IR sensor also impresses with its ease of installation.",
    specs: [
      { label: "Application, place", value: "Outdoors, Indoors" },
      { label: "Installation", value: "Surface wiring" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "Ø 7 m (38 m²)" },
      { label: "Mounting height max.", value: "4,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "white" },
      { label: "PU1, net weight", value: "0,12 kg" },
      { label: "infrared sensor 360°", value: "max. 7 m" },
      { label: "max. 2000 W", value: "IP54" },
      { label: "2 - 2000 lux", value: "8 sec - 35 min" },
      { label: "manufacturer's warranty steinel.de/garantie", value: "CE" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-is-2360-s.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-is-2360-s",
  },
  {
    slug: "steinel-light-sensor",
    name: "Light Sensor",
    category: "sensors",
    supplier: "Steinel",
    summary: "Light Sensor — Light Sensor supplied by LumenX.",
    description: "Light Sensor — Light Sensor supplied by LumenX.",
    specs: [
      { label: "Application, place", value: "Outdoors" },
      { label: "Installation", value: "Surface wiring" },
      { label: "Mounting height max.", value: "4,00 m" },
      { label: "Interconnection via", value: "Bluetooth Mesh" },
      { label: "Version", value: "Anthracite" },
      { label: "PU1, net weight", value: "0,125 kg" },
      { label: "15 lux", value: "IP54" },
      { label: "connectable via bluetooth", value: "CE" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/steinel-light-sensor",
  },
  {
    slug: "steinel-dualtech",
    name: "DualTech",
    category: "sensors",
    supplier: "Steinel",
    summary: "Risk of electric shock! 230 V means danger to life! Disconnect the power supply before attempting any work on the product. Durin…",
    description: "Risk of electric shock! 230 V means danger to life! Disconnect the power supply before attempting any work on the product. During installation, the electric power cable being connected may not be live. Therefore, switch off the power first and use a voltage tester to make sure the wiring is off-circuit. Installing the sensor involves work on the mains power supply. This work must therefore be carried out professionally in accordance with national wiring regulations and electrical operating conditions. (e.g. DE - VDE 0100, AT - ÖVE / ÖNORM E8001-1, CH - SEV 1000) For products with COM2 port: connection B1, B2 is a switching contact for low-energy circuits. This must be fuse-protected in line with the technical specifications. Only electronic ballasts with a floating control signal may be used at the DIM 1 to 10 V control output. No mains voltage may be connected to control output/input DA+ / DA-. Only use genuine replacement parts. Repairs may only be made by specialist workshops.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "In-ceiling installation" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "Ultrasonic: Ultraschall: Ø 10 m (Ultraschall: 79 m²)" },
      { label: "Mounting height max.", value: "3,50 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - in-ceiling installation" },
      { label: "PU1, net weight", value: "0,225 kg" },
      { label: "ultrasonic sensor 360°", value: "infrared sensor 360°" },
      { label: "max. Ø 6 m presence", value: "max. 2000 W" },
      { label: "IP20", value: "ideal 2,5 - 3,5 m" },
      { label: "indoor sensor", value: "IQ-mode" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-dualtech.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-dualtech",
  },
  {
    slug: "steinel-is-3360",
    name: "IS 3360",
    category: "sensors",
    supplier: "Steinel",
    summary: "Higher, further, faster. Infrared presence detector IS 3360 for indoors and out, ideal for watching over high spaces and large a…",
    description: "Higher, further, faster. Infrared presence detector IS 3360 for indoors and out, ideal for watching over high spaces and large areas, such as multi-storey and underground car parks, installation height up to 4 m, 360° angle of coverage, reach 20 m max. (tangential), heavy-duty relay for high switching capacity. Available either in round or square surface-mounted, concealed or In-ceiling installation.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "In-ceiling installation" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "Ø 40 m (1257 m²)" },
      { label: "Mounting height max.", value: "4,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - in-ceiling installation, rd. white" },
      { label: "PU1, net weight", value: "0,161 kg" },
      { label: "infrared sensor 360°", value: "max. 20 m" },
      { label: "max. 2000 W", value: "IP20" },
      { label: "2 - 1000 lux", value: "5 sec - 15 min" },
      { label: "manual override", value: "ideal 2,5 - 4 m" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-is-3360.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-is-3360",
  },
  {
    slug: "steinel-is-3360-highbay",
    name: "IS 3360 Highbay",
    category: "sensors",
    supplier: "Steinel",
    summary: "A head for heights. Powerful reach. Reliable. IS 3360 MX Highbay motion detector – ideal for high ceilings in industrial buildin…",
    description: "A head for heights. Powerful reach. Reliable. IS 3360 MX Highbay motion detector – ideal for high ceilings in industrial buildings or commercial properties. For mounting heights of up to 14 m. High-precision 360° infrared sensor. Maximum reach: 18 m. For watching over up to 1000 sq.m. Available as square surface-mounted and concealed version.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "Surface wiring" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "Ø 36 m (1018 m²)" },
      { label: "Mounting height max.", value: "14,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - surface, sq." },
      { label: "PU1, net weight", value: "0,176 kg" },
      { label: "infrared sensor 360°", value: "18 m" },
      { label: "max. 2000 W", value: "IP54" },
      { label: "2 - 1000 lux", value: "5 sec - 15 min" },
      { label: "manual override", value: "ideal 4 - 14 m" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-is-3360-highbay.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-is-3360-highbay",
  },
  {
    slug: "steinel-is-345-highbay",
    name: "IS 345 Highbay",
    category: "sensors",
    supplier: "Steinel",
    summary: "Surveillance on the highest level. Infrared motion detector IS 345 MX Highbay for indoors, ideal for large heights in depots, hi…",
    description: "Surveillance on the highest level. Infrared motion detector IS 345 MX Highbay for indoors, ideal for large heights in depots, high-bay warehouses, machine shops, check-in areas and departure lounges, installation height 16 m, detection zone 30 x 4 m (radial), large terminal compartment for easy installation, heavy-duty relay for high switching capacity. Available as square surface-mounted and concealed version.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "Surface wiring" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "30 x 4 m (120 m²)" },
      { label: "Mounting height max.", value: "16,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - surface, sq." },
      { label: "PU1, net weight", value: "0,176 kg" },
      { label: "infrared sensor 360°", value: "max. 30 x 4 m" },
      { label: "max. 2000 W", value: "IP54" },
      { label: "2 - 1000 lux", value: "5 sec - 15 min" },
      { label: "manual override", value: "Teach mode" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-is-345-highbay.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-is-345-highbay",
  },
  {
    slug: "steinel-dual-hf-corridor",
    name: "Dual HF Corridor",
    category: "sensors",
    supplier: "Steinel",
    summary: "Twice as vigilant! High-frequency corridor sensor Presence Control PRO Dual HF COM1 for indoors, ideal for passageways and long …",
    description: "Twice as vigilant! High-frequency corridor sensor Presence Control PRO Dual HF COM1 for indoors, ideal for passageways and long corridors, installation height up to 3.5 m, for switching light 'ON' and 'OFF', DUAL-HF technology for detecting radial movement over up to 20 m in two directions, detection regardless of temperature, HF-sensor technology detects movement through glass, wood and stud walls, switches light 'ON' almost instantly.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "In-ceiling installation" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "20 x 3 m (60 m²)" },
      { label: "Mounting height max.", value: "3,50 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - in-ceiling installation" },
      { label: "PU1, net weight", value: "0,236 kg" },
      { label: "high frequency sensor 360°", value: "max. 20 x 3 m" },
      { label: "max. 2000 W", value: "IP20" },
      { label: "ideal 2,5 - 3,5 m", value: "indoor sensor" },
      { label: "IQ-mode", value: "Teach mode" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-dual-hf-corridor.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-dual-hf-corridor",
  },
  {
    slug: "steinel-hf-360",
    name: "HF 360",
    category: "sensors",
    supplier: "Steinel",
    summary: "Doesn't miss a thing. HF-presence detector Presence Control PRO HF 360 COM1 for indoors, ideal for WCs with toilet cubicles, cha…",
    description: "Doesn't miss a thing. HF-presence detector Presence Control PRO HF 360 COM1 for indoors, ideal for WCs with toilet cubicles, changing rooms, stairwells, multi-storey car parks, kitchens, installation height up to 3.5 m, for switching light 'ON' and 'OFF', 1 – 12 m reach, reach is electronically adjustable and can be limited in two directions, detection regardless of temperature, HF-sensor technology also detects movement through glass, wood and stud walls.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "In-ceiling installation" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "Ø 12 m (113 m²)" },
      { label: "Mounting height max.", value: "3,50 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - in-ceiling installation" },
      { label: "PU1, net weight", value: "0,185 kg" },
      { label: "high frequency sensor 360°", value: "max. Ø 12 m" },
      { label: "max. 2000 W", value: "IP20" },
      { label: "ideal 2,5 - 3,5 m", value: "indoor sensor" },
      { label: "IQ-mode", value: "Teach mode" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-hf-360.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-hf-360",
  },
  {
    slug: "steinel-is-2180",
    name: "IS 2180",
    category: "sensors",
    supplier: "Steinel",
    summary: "Attractive, clever, efficient. Infrared motion detector IS 2180-2 for outdoors, ideal for building fronts and properties, medium…",
    description: "Attractive, clever, efficient. Infrared motion detector IS 2180-2 for outdoors, ideal for building fronts and properties, medium-sized business and outdoor spaces, ideal installation height 2 m, 180° angle of coverage, reach. 12 m max. or 5 m max. (tangential), selectable time and twilight threshold, manual override, for outdoor and indoor installation .",
    specs: [
      { label: "Application, place", value: "Outdoors, Indoors" },
      { label: "Installation", value: "Surface wiring" },
      { label: "Detection angle", value: "180 °" },
      { label: "Reach, tangential", value: "r = 5 m (39 m²) / r = 12 m (226 m²)" },
      { label: "Mounting height max.", value: "4,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "white" },
      { label: "PU1, net weight", value: "0,12 kg" },
      { label: "infrared sensor 180°", value: "max. Ø 12 m" },
      { label: "1000 W max.", value: "IP54" },
      { label: "2 - 2000 lux", value: "5 sec - 15 min" },
      { label: "manufacturer's warranty steinel.de/garantie", value: "CE" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-is-2180.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-is-2180",
  },
  {
    slug: "steinel-ir-quattro-micro",
    name: "IR Quattro Micro",
    category: "sensors",
    supplier: "Steinel",
    summary: "Noticeably Inconspicuous. IR Quattro SLIM XS, the extra-slim presence detector in concealed-box format. Fits into any standard c…",
    description: "Noticeably Inconspicuous. IR Quattro SLIM XS, the extra-slim presence detector in concealed-box format. Fits into any standard concealed box. Overall height of just 6 mm. High-precision 360° infrared senor with globally unique retina lens and 16 sq.m square presence detection zone (4 x 4 m). Adjustment via remote control or Smart Remote. Round aperture is additionally enclosed.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "Concealed wiring" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "4 x 4 m (16 m²)" },
      { label: "Mounting height max.", value: "4,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - square" },
      { label: "PU1, net weight", value: "0,078 kg" },
      { label: "infrared sensor", value: "max. 4 x 4 m presence" },
      { label: "IP20", value: "1000 W max." },
      { label: "10 - 1000 lux with RC 8", value: "1 min - 15 min with RC 8" },
      { label: "ideal 2,5 - 4 m", value: "Teach mode" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-ir-quattro-micro.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-ir-quattro-micro",
  },
  {
    slug: "steinel-ir-quattro-hd",
    name: "IR Quattro HD",
    category: "sensors",
    supplier: "Steinel",
    summary: "Detection no finer! Infrared presence detector Presence Control PRO IR Quattro HD COM1 for indoors, ideal for medium to large-si…",
    description: "Detection no finer! Infrared presence detector Presence Control PRO IR Quattro HD COM1 for indoors, ideal for medium to large-size offices, conference and meeting rooms, classrooms and lecture theatres, sports halls and warehouses, installation height up to 10 m, for switching light 'ON' and 'OFF', 4800 switching zones for the ultimate in detection quality, presence detection over a true 64 m2, square detection zone, mechanically scalable.",
    specs: [
      { label: "Application, place", value: "Indoors" },
      { label: "Installation", value: "In-ceiling installation" },
      { label: "Detection angle", value: "360 °" },
      { label: "Reach, tangential", value: "20 x 20 m (400 m²)" },
      { label: "Mounting height max.", value: "10,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "COM1 - in-ceiling installation white" },
      { label: "PU1, net weight", value: "0,216 kg" },
      { label: "infrared sensor", value: "max. 8m x 8m presence" },
      { label: "4800 zones", value: "max. 2000 W" },
      { label: "ideal 2,5 - 10 m", value: "indoor sensor" },
      { label: "manufacturer's warranty steinel.de/garantie", value: "CE" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-ir-quattro-hd.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-ir-quattro-hd",
  },
  {
    slug: "steinel-sensiq-s",
    name: "Sens IQ S",
    category: "sensors",
    supplier: "Steinel",
    summary: "Sens IQ S — Sens IQ S supplied by LumenX.",
    description: "Sens IQ S — Sens IQ S supplied by LumenX.",
    specs: [
      { label: "Application, place", value: "Indoors, Outdoors" },
      { label: "Installation", value: "Surface wiring" },
      { label: "Detection angle", value: "300 °" },
      { label: "Reach, tangential", value: "r = 20 m (1047 m²)" },
      { label: "Mounting height max.", value: "5,00 m" },
      { label: "Interconnection via", value: "Cable" },
      { label: "Version", value: "white" },
      { label: "PU1, net weight", value: "0,252 kg" },
      { label: "infrared sensor 3 x 100°", value: "3 zones scalable 2-20m" },
      { label: "max. 2000 W", value: "IP54" },
      { label: "2 - 2000 lux daylight operation", value: "5 sec - 15 min" },
      { label: "ideal 2 - 5 m", value: "Teach mode" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-sensiq-s.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-sensiq-s",
  },
  {
    slug: "steinel-smart-remote",
    name: "Smart Remote",
    category: "sensors",
    supplier: "Steinel",
    summary: "Smart Remote — Smart Remote supplied by LumenX.",
    description: "Smart Remote — Smart Remote supplied by LumenX.",
    specs: [
      { label: "PU1, net weight", value: "0,057 kg" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-smart-remote.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-smart-remote",
  },
  {
    slug: "steinel-service-remote",
    name: "Service Remote",
    category: "sensors",
    supplier: "Steinel",
    summary: "The full works at the press of a button. User remote control RC7 KNX for Presence Control PRO presence detectors and motion dete…",
    description: "The full works at the press of a button. User remote control RC7 KNX for Presence Control PRO presence detectors and motion detectors in conjunction with KNX interface.",
    specs: [
      { label: "PU1, net weight", value: "0,056 kg" },
    ],
    features: [],
    applications: ["Offices","Warehouses","Corridors","Security"],
    imageUrl: "/product-images/steinel-service-remote.png",
    pdfUrl: "/api/download/datasheet/generated/steinel-service-remote",
  },
  {
    slug: "kinglong-cloud-bell-series",
    name: "Cloud Bell",
    category: "decorative",
    supplier: "KingLong",
    summary: "The Cloud Bell Series draws its vocabulary from the gentle curves of hanging bells and the soft fullness of clouds at dusk — org…",
    description: "The Cloud Bell Series draws its vocabulary from the gentle curves of hanging bells and the soft fullness of clouds at dusk — organic forms that carry both visual weight and an inherent sense of movement. Each bell element is individually crafted from layered acrylic and crystal, achieving a depth of luminous translucency that flat surfaces cannot replicate. Deployed in clusters of varying heights, the Cloud Bell Series creates installations that feel more like kinetic sculpture than conventional lighting — ideal for clients who treat their spaces as galleries of lived experience.",
    specs: [
      { label: "Light Source", value: "Integrated LED, 2700K / 3000K CCT, CRI > 90" },
      { label: "IP Rating", value: "IP20 standard" },
      { label: "Lead Time", value: "Standard: 5–7 weeks · Grand Installation: 10–16 weeks" },
      { label: "Wattage", value: "15W – 500W (configuration-dependent)" },
      { label: "Voltage", value: "110V – 240V, 50/60Hz Universal Input" },
      { label: "Dimming", value: "0–10V · Triac · DALI" },
      { label: "Primary Material", value: "Layered Optical Acrylic + K9 Crystal Accent Elements" },
      { label: "Frame", value: "Stainless Steel 304 PVD-coated" },
      { label: "Finish Options", value: "Champagne Gold · Matte Black · Brushed Silver" },
      { label: "Warranty", value: "3 Years · LED Driver: 5 Years" },
      { label: "Certifications", value: "CE · CNAS-accredited test reports available" },
    ],
    features: [],
    applications: ["Hospitality","Residential","Lobbies","Retail"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/kinglong-cloud-bell-series",
  },
  {
    slug: "kinglong-pearl-series",
    name: "Pearl Series",
    category: "decorative",
    supplier: "KingLong",
    summary: "Pearls have symbolised purity and refinement across cultures for millennia — and the Pearl Series channels that same quiet confi…",
    description: "Pearls have symbolised purity and refinement across cultures for millennia — and the Pearl Series channels that same quiet confidence into decorative lighting. Each sphere is crafted from high-quality mouth-blown glass, achieving a uniformity of form and a translucency that mass-produced alternatives cannot match. Arranged in cascading cluster configurations that echo the natural randomness of a pearl strand, the series brings an organic, timeless elegance to any interior. Versatile enough for both intimate residential dining rooms and the public areas of boutique hotels, the Pearl Series is a perennial bestseller.",
    specs: [
      { label: "Light Source", value: "G9 LED / Integrated LED Module, 2700K / 3000K CCT, CRI > 90" },
      { label: "IP Rating", value: "IP20 standard" },
      { label: "Lead Time", value: "Standard: 4–6 weeks · Custom: 6–10 weeks" },
      { label: "Wattage", value: "5W – 200W (sphere count-dependent)" },
      { label: "Voltage", value: "110V – 240V, 50/60Hz Universal Input" },
      { label: "Dimming", value: "Triac · 0–10V" },
      { label: "Primary Material", value: "High-Quality Mouth-Blown Glass Spheres" },
      { label: "Alternative", value: "High-Clarity Optical Acrylic Spheres (lightweight variant)" },
      { label: "Frame", value: "Stainless Steel Cable + Brass / Chrome Cap Fittings" },
      { label: "Finish Options", value: "Champagne Gold · Chrome · Antique Brass · Matte Black" },
      { label: "Sphere Diameter Options", value: "Ø60 / Ø80 / Ø100 / Ø150 / Ø200mm" },
      { label: "Cluster Configurations", value: "9-sphere / 18-sphere / 36-sphere / custom" },
      { label: "Warranty", value: "3 Years · LED Driver: 5 Years" },
      { label: "Certifications", value: "CE · CNAS-accredited test reports available" },
    ],
    features: [],
    applications: ["Hospitality","Residential","Lobbies","Retail"],
    imageUrl: "/product-images/kinglong-pearl-series.png",
    pdfUrl: "/api/download/datasheet/generated/kinglong-pearl-series",
  },
  {
    slug: "dream-pen",
    name: "Dream Pen",
    category: "decorative",
    supplier: "KingLong",
    summary: "Dream Pen — Dream Pen supplied by LumenX.",
    description: "Dream Pen — Dream Pen supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Hospitality","Residential","Feature interiors"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "kinglong-jiangnan-series",
    name: "Jiangnan",
    category: "decorative",
    supplier: "KingLong",
    summary: "Inspired by the poetic mist-veiled landscapes of Jiangnan — southern China's storied water towns — this collection translates Ea…",
    description: "Inspired by the poetic mist-veiled landscapes of Jiangnan — southern China's storied water towns — this collection translates Eastern sensibility into a thoroughly contemporary design language. High-quality eco-leather wraps a precision metal armature, creating a signature softness that diffuses light with warmth and intimacy. The Champagne Gold PVD-finished metal structure offers outstanding durability and corrosion resistance, making it ideal for demanding hospitality environments. Recognized by international design awards, the Jiangnan Series redefines what modern Chinese-inspired lighting can be.",
    specs: [
      { label: "Light Source", value: "Integrated LED, 2700K / 3000K CCT, CRI > 90" },
      { label: "IP Rating", value: "IP20 standard" },
      { label: "Lead Time", value: "Standard: 5–7 weeks · Bespoke: 10–16 weeks" },
      { label: "Awards", value: "UK Birmingham Lighting Design of the Year (2010)" },
      { label: "Wattage", value: "18W – 300W (configuration-dependent)" },
      { label: "Voltage", value: "110V – 240V, 50/60Hz Universal Input" },
      { label: "Dimming", value: "DALI · 0–10V · Triac" },
      { label: "Primary Material", value: "High-Grade Eco-Leather (Simulated Leather) + Stainless Steel Frame" },
      { label: "Accent Material", value: "Optical Acrylic Diffuser" },
      { label: "Frame", value: "Finish Champagne Gold PVD (standard) · Matte Black · Brushed Nickel" },
      { label: "Size Range", value: "Single pendant: Ø400–Ø1200mm · Linear: L600–L2400mm" },
      { label: "Installation", value: "Suspension cable system · Adjustable height" },
      { label: "Warranty", value: "3 Years · LED Driver: 5 Years" },
      { label: "Certifications", value: "CE · UL · CNAS-accredited test reports available" },
    ],
    features: [],
    applications: ["Hospitality","Residential","Lobbies","Retail"],
    imageUrl: "/product-images/kinglong-jiangnan-series.png",
    pdfUrl: "/api/download/datasheet/generated/kinglong-jiangnan-series",
  },
  {
    slug: "kinglong-crystal-cloud-series",
    name: "Crystal Cloud",
    category: "decorative",
    supplier: "KingLong",
    summary: "The Crystal Cloud Series is pure poetry rendered in light. Thousands of individually placed crystal elements are suspended at va…",
    description: "The Crystal Cloud Series is pure poetry rendered in light. Thousands of individually placed crystal elements are suspended at varied heights, creating an immersive three-dimensional cloud formation that hovers above the space below. In motion with air currents, the installation breathes and shimmers — transforming any room it occupies into an experiential destination. Designed for the most ambitious architectural briefs, the Crystal Cloud Series has graced the lobbies of Ritz-Carlton, Four Seasons, and Shangri-La properties worldwide.",
    specs: [
      { label: "Light Source", value: "Integrated LED, 2700K / 3000K CCT, CRI > 90" },
      { label: "IP Rating", value: "IP20 standard" },
      { label: "Lead Time", value: "Standard: 6–8 weeks · Grand Installation: 12–20 weeks" },
      { label: "Wattage", value: "40W – 1200W+ (installation-scale dependent)" },
      { label: "Voltage", value: "110V – 240V, 50/60Hz Universal Input" },
      { label: "Dimming", value: "DALI · 0–10V · DMX (for dynamic scene control)" },
      { label: "Primary Material", value: "Premium K9 Crystal Pendants (multi-cut facets)" },
      { label: "Frame", value: "Stainless Steel 304, PVD finished" },
      { label: "Finish Options", value: "Champagne Gold PVD · Chrome · Rose Gold" },
      { label: "Installation Scale", value: "Ø1200mm single cluster to full atrium bespoke installation" },
      { label: "Crystal Count", value: "200 pcs (small) to 20,000+ pcs (grand installation)" },
      { label: "Warranty", value: "3 Years · LED Driver: 5 Years" },
      { label: "Certifications", value: "UL · CE · SASO · CNAS-accredited test reports available" },
    ],
    features: [],
    applications: ["Hospitality","Residential","Lobbies","Retail"],
    imageUrl: "/product-images/kinglong-crystal-cloud-series.png",
    pdfUrl: "/api/download/datasheet/generated/kinglong-crystal-cloud-series",
  },
  {
    slug: "ledsc4-circular-10002",
    name: "Circular",
    category: "indoor-architectural",
    supplier: "LEDsC4",
    summary: "Harmony closes in a circle.",
    description: "Harmony closes in a circle.",
    specs: [
      { label: "Lumen Output", value: "2133–49034 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "CRI", value: "92" },
      { label: "Wattage", value: "33–575 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Three light directions: interior, exterior, and underneath.","Available in three finishes: white, black, and gold","Possibility of recessed or surface installation","Multiple compositions, both vertical and horizontal, in a simple or chandelier version."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-circular-10002.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-circular-10002",
  },
  {
    slug: "ledsc4-circular-vertical-10374",
    name: "Circular Vertical",
    category: "indoor-architectural",
    supplier: "LEDsC4",
    summary: "Harmony closes in a circle.",
    description: "Harmony closes in a circle.",
    specs: [
      { label: "Lumen Output", value: "2225–6116 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "CRI", value: "92" },
      { label: "Wattage", value: "39–72 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Three light directions: interior, exterior, and underneath.","Available in three finishes: white, black, and gold","Possibility of recessed or surface installation","Multiple compositions, both vertical and horizontal, in a simple or chandelier version."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-circular-vertical-10374.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-circular-vertical-10374",
  },
  {
    slug: "ledsc4-attic-10009",
    name: "Attic",
    category: "indoor-architectural",
    supplier: "LEDsC4",
    summary: "Attic — Attic supplied by LumenX.",
    description: "Attic — Attic supplied by LumenX.",
    specs: [
      { label: "Lumen Output", value: "768–4340 lm" },
    ],
    features: [],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-attic-10009",
  },
  {
    slug: "ledsc4-vetro-10124",
    name: "Vetro",
    category: "indoor-architectural",
    supplier: "LEDsC4",
    summary: "Essential that resists moisture",
    description: "Essential that resists moisture",
    specs: [
      { label: "Lumen Output", value: "1240 lm" },
      { label: "Colour Temperature", value: "3000K" },
      { label: "CRI", value: "80" },
      { label: "IP Rating", value: "IP44" },
      { label: "Wattage", value: "22.4 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["Waterproof properties with IP44","Highly resistant with IK05","Double pressed glass"],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-vetro-10124.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-vetro-10124",
  },
  {
    slug: "superlume-fabric-tape",
    name: "Fabric Tape",
    category: "indoor-architectural",
    supplier: "Superlume",
    summary: "Fabric Tape — Fabric Tape supplied by LumenX.",
    description: "Fabric Tape — Fabric Tape supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Offices","Retail","Hospitality"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "ledsc4-eko-10141",
    name: "Eko",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Essential with a filter that softens the light effect",
    description: "Essential with a filter that softens the light effect",
    specs: [
      { label: "Lumen Output", value: "278–1379 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K" },
    ],
    features: ["Includes bulb extraction kit","In vertical downward position, excellent visual comfort. Index: BUG B1 U0 G0.","LED models with a lifespan of 50,000h L80 B20.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-eko-10141.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-eko-10141",
  },
  {
    slug: "ledsc4-cube-spot-10301",
    name: "Cube",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Maximum precision for high-rise facades",
    description: "Maximum precision for high-rise facades",
    specs: [
      { label: "Lumen Output", value: "213–6451 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "3.6–321 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Includes wiring with waterproof quick connectors","In vertical downward position, excellent visual comfort. Index: BUG B0 U0 G0.","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-cube-spot-10301.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-cube-spot-10301",
  },
  {
    slug: "ledsc4-hubble-10143",
    name: "Hubble",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Collection of versatile and highly efficient projectors",
    description: "Collection of versatile and highly efficient projectors",
    specs: [
      { label: "Lumen Output", value: "224–10863 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "8–968 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Quick and waterproof connection wiring","In vertical downward position, excellent visual comfort. Index: BUG B3 U0 G0.","LED models with a lifespan of 50,000h L80 B20","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-hubble-10143.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-hubble-10143",
  },
  {
    slug: "ledsc4-eko-10195",
    name: "Eko",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Essential with premium features",
    description: "Essential with premium features",
    specs: [
      { label: "Lumen Output", value: "278–369 lm" },
      { label: "Colour Temperature", value: "3000K" },
    ],
    features: ["Standard version and with tilted head","Zero light pollution (ULOR: 0%) and BUG B1 U0 G0.","LED models with a lifespan of 50,000h L80 B20","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-eko-10195.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-eko-10195",
  },
  {
    slug: "ledsc4-ele-10311",
    name: "Ele",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Pure aesthetics for greater comfort",
    description: "Pure aesthetics for greater comfort",
    specs: [
      { label: "Lumen Output", value: "871–968 lm" },
      { label: "Colour Temperature", value: "2200K / 2700K / 3000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "10.3 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["LED and driver easily replaceable.","Zero light pollution (ULOR: 0%) and BUG B1 U0 G0.","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-ele-10311.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-ele-10311",
  },
  {
    slug: "ledsc4-modis-10316",
    name: "Modis",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Modis — Modis supplied by LumenX.",
    description: "Modis — Modis supplied by LumenX.",
    specs: [
      { label: "Lumen Output", value: "932–2080 lm" },
      { label: "Colour Temperature", value: "2200K / 2700K / 3000K / 3200K / 4000K" },
      { label: "Input Voltage", value: "100-277V" },
    ],
    features: [],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-modis-10316",
  },
  {
    slug: "ledsc4-moal-10202",
    name: "Moal",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Furniture and light beacon",
    description: "Furniture and light beacon",
    specs: [
      { label: "Lumen Output", value: "729 lm" },
      { label: "Colour Temperature", value: "3000K" },
      { label: "CRI", value: "92" },
      { label: "IP Rating", value: "IP66" },
      { label: "Wattage", value: "16.3 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["Protection against impacts and high-pressure water (IK10 and IP66)","Available in two sizes","LED with 50,000h L80 B20 lifespan","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-moal-10202.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-moal-10202",
  },
  {
    slug: "ledsc4-row-10319",
    name: "Row",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Integration in cement",
    description: "Integration in cement",
    specs: [
      { label: "Lumen Output", value: "1071 lm" },
      { label: "Colour Temperature", value: "3000K" },
      { label: "CRI", value: "80" },
      { label: "IP Rating", value: "IP66" },
      { label: "Wattage", value: "19.3 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["Protection against dust and high-pressure water (IK10 and IP66)","Made 100% of cement","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-row-10319.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-row-10319",
  },
  {
    slug: "ledsc4-ele-10218",
    name: "Ele",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Pure aesthetics for greater comfort",
    description: "Pure aesthetics for greater comfort",
    specs: [
      { label: "Lumen Output", value: "2456–5458 lm" },
      { label: "Colour Temperature", value: "2200K / 2700K / 3000K" },
      { label: "CRI", value: "80" },
      { label: "IP Rating", value: "IP66" },
      { label: "Wattage", value: "26–49 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["Protection against dust and high-pressure water (IK10 and IP66)","BREEAM certification","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-ele-10218.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-ele-10218",
  },
  {
    slug: "ledsc4-proud-10224",
    name: "Proud",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Adaptable personality",
    description: "Adaptable personality",
    specs: [
      { label: "Lumen Output", value: "0–3421 lm" },
      { label: "Colour Temperature", value: "3000K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "44.9 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["BREEAM certification","LED and driver easily replaceable.","L80 B20 50,000h lifespan.","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-proud-10224.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-proud-10224",
  },
  {
    slug: "ledsc4-lyon-10221",
    name: "Lyon",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Extensive lighting",
    description: "Extensive lighting",
    specs: [
      { label: "Lumen Output", value: "0–4741 lm" },
      { label: "Colour Temperature", value: "2700K / 3200K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "IP Rating", value: "IP66" },
      { label: "Wattage", value: "55 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["Protection against dust and high-pressure water (IK10 and IP66)","BREEAM certification","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-lyon-10221.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-lyon-10221",
  },
  {
    slug: "ledsc4-zigzag-10225",
    name: "Zig Zag",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Español English Deutsch Français Italiano Português Polski Русский",
    description: "Español English Deutsch Français Italiano Português Polski Русский",
    specs: [
      { label: "Lumen Output", value: "0–5595 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "62.1 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["LED and driver easily replaceable.","Zero light pollution (ULOR: 0%)","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-zigzag-10225.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-zigzag-10225",
  },
  {
    slug: "ledsc4-helion-10219",
    name: "Helion",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Evocative lights and shadows",
    description: "Evocative lights and shadows",
    specs: [
      { label: "Lumen Output", value: "1323 lm" },
      { label: "Colour Temperature", value: "2700K / 3200K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "22 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Switch 2700 K - 3200K - 4000K included","BREEAM certification","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-helion-10219.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-helion-10219",
  },
  {
    slug: "ledsc4-cube-linear-recessed-10128",
    name: "Cube Linear",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Maximum precision to wash high-rise facades",
    description: "Maximum precision to wash high-rise facades",
    specs: [
      { label: "Lumen Output", value: "1344–8888 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "CRI", value: "70" },
      { label: "Wattage", value: "24.5–676 W" },
      { label: "Input Voltage", value: "220-240V" },
    ],
    features: ["Includes flush-mounted box and metal connection plates","Includes wiring with waterproof quick connectors","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-cube-linear-recessed-10128.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-cube-linear-recessed-10128",
  },
  {
    slug: "ledsc4-gea-cob-10155",
    name: "Gea Cob",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Ideal swivel solution for vegetation",
    description: "Ideal swivel solution for vegetation",
    specs: [
      { label: "Lumen Output", value: "869–5878 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
    ],
    features: [],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-gea-cob-10155.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-gea-cob-10155",
  },
  {
    slug: "ledsc4-finestra-10183",
    name: "Finestra",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Customizable facades",
    description: "Customizable facades",
    specs: [
      { label: "Lumen Output", value: "281–414 lm" },
      { label: "Colour Temperature", value: "4000K" },
      { label: "CRI", value: "80" },
      { label: "IP Rating", value: "IP66" },
      { label: "Wattage", value: "5.4–10.8 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Protection against dust and high-pressure water (IK10 and IP66)","Standard option or DMX","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-finestra-10183.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-finestra-10183",
  },
  {
    slug: "ledsc4-cosmos-10172",
    name: "Cosmos",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Elegance and versatility",
    description: "Elegance and versatility",
    specs: [
      { label: "Lumen Output", value: "972–3678 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "11.8–36 W" },
      { label: "Input Voltage", value: "100-240V" },
    ],
    features: ["Energy efficiency with BREEAM certification","Custom finishes available upon request","50,000h L80 B20 useful life.","5-year warranty for heavy use (4,000 hours/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-cosmos-10172.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-cosmos-10172",
  },
  {
    slug: "ledsc4-afrodita-led-10168",
    name: "Afrodita",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Afrodita — Afrodita supplied by LumenX.",
    description: "Afrodita — Afrodita supplied by LumenX.",
    specs: [
      { label: "Lumen Output", value: "1084–4049 lm" },
      { label: "Colour Temperature", value: "2700K / 3000K / 4000K" },
      { label: "Input Voltage", value: "220-240V" },
    ],
    features: [],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-afrodita-led-10168",
  },
  {
    slug: "ledsc4-mega-10230",
    name: "Mega",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Lighting of large surfaces",
    description: "Lighting of large surfaces",
    specs: [
      { label: "Lumen Output", value: "8303 lm" },
      { label: "Colour Temperature", value: "3000K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "Wattage", value: "81.4 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: [],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-mega-10230.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-mega-10230",
  },
  {
    slug: "ledsc4-cisne-colgante-10231",
    name: "Cisne Colgante",
    category: "outdoor-architectural",
    supplier: "LEDsC4",
    summary: "Warmth and magnetism",
    description: "Warmth and magnetism",
    specs: [
      { label: "Lumen Output", value: "0–653 lm" },
      { label: "Colour Temperature", value: "2700K / 3200K / 4000K" },
      { label: "CRI", value: "80" },
      { label: "IP Rating", value: "IP66" },
      { label: "Wattage", value: "7.1 W" },
      { label: "Input Voltage", value: "220V" },
    ],
    features: ["Protection against dust and high-pressure water (IK10 and IP66)","LED modules and E27 easily replaceable.","LED models with a lifespan of 50,000h L80 B20.","5-year warranty for heavy use (4,000h/year) and in a marine atmosphere."],
    applications: ["Architectural","Commercial","Hospitality"],
    imageUrl: "/product-images/ledsc4-cisne-colgante-10231.png",
    pdfUrl: "/api/download/datasheet/generated/ledsc4-cisne-colgante-10231",
  },
  {
    slug: "superlume-palm-and-coco",
    name: "Palm & Coco",
    category: "outdoor-architectural",
    supplier: "Superlume",
    summary: "Palm & Coco — Palm & Coco supplied by LumenX.",
    description: "Palm & Coco — Palm & Coco supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Facades","Pathways","Landscape","Municipal"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "fuji-square",
    name: "Fuji Square",
    category: "outdoor-architectural",
    supplier: "Pioled",
    summary: "Fuji Square — Fuji Square supplied by LumenX.",
    description: "Fuji Square — Fuji Square supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Facades","Pathways","Landscape","Municipal"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "fuji-round",
    name: "Fuji Round",
    category: "outdoor-architectural",
    supplier: "Pioled",
    summary: "Fuji Round — Fuji Round supplied by LumenX.",
    description: "Fuji Round — Fuji Round supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Facades","Pathways","Landscape","Municipal"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "everest-square",
    name: "Everest Square",
    category: "outdoor-architectural",
    supplier: "Pioled",
    summary: "Everest Square — Everest Square supplied by LumenX.",
    description: "Everest Square — Everest Square supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Facades","Pathways","Landscape","Municipal"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "everest-round",
    name: "Everest Round",
    category: "outdoor-architectural",
    supplier: "Pioled",
    summary: "Everest Round — Everest Round supplied by LumenX.",
    description: "Everest Round — Everest Round supplied by LumenX.",
    specs: [
    ],
    features: [],
    applications: ["Facades","Pathways","Landscape","Municipal"],
    imageUrl: "/product-images/placeholder-product.svg",
  },
  {
    slug: "zod101-square-led-wall",
    name: "ZOD101 Square LED Wall",
    category: "outdoor-architectural",
    supplier: "Superlume",
    summary: "ZOD101 Square LED Wall — decorative wall light from Superlume: IP65 rated, 12W with up to 1200 lm in 4000K, designed for covered…",
    description: "ZOD101 Square LED Wall — decorative wall light from Superlume: IP65 rated, 12W with up to 1200 lm in 4000K, designed for covered and outdoor wall mounting.",
    specs: [
      { label: "Nominal Flux", value: "Up to 1200 lm" },
      { label: "Efficacy", value: "Up to 100 lm/w" },
      { label: "Colour Temperature", value: "4000k" },
      { label: "CRI", value: ">80" },
      { label: "Power Factor", value: "0,9" },
      { label: "IP Rating", value: "IP65" },
      { label: "Wattage", value: "12W" },
      { label: "Input Voltage", value: "220-240V" },
      { label: "Body", value: "Polycarbonate" },
      { label: "Diffuser", value: "Polycarbonate" },
      { label: "Mounting", value: "Wall Mount" },
      { label: "Colour", value: "Black" },
      { label: "Product Size (L × W × H)", value: "169mm x 67mm x 169mm" },
      { label: "Product Weight", value: "0,68kg" },
    ],
    features: [],
    applications: ["Outdoor walls","Facades","Entrances"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/zod101-square-led-wall",
  },
  {
    slug: "zod102-round-led-wall",
    name: "ZOD102 Round LED Wall",
    category: "outdoor-architectural",
    supplier: "Superlume",
    summary: "ZOD102 Round LED Wall — decorative coastal-ready wall light from Superlume: IP65 rated, 12W with up to 1200 lm in 4000K, designe…",
    description: "ZOD102 Round LED Wall — decorative coastal-ready wall light from Superlume: IP65 rated, 12W with up to 1200 lm in 4000K, designed for covered and outdoor wall mounting.",
    specs: [
      { label: "Nominal Flux", value: "Up to 1200 lm" },
      { label: "Efficacy", value: "Up to 100 lm/w" },
      { label: "Colour Temperature", value: "4000k" },
      { label: "CRI", value: ">80" },
      { label: "Power Factor", value: "0,9" },
      { label: "IP Rating", value: "IP65" },
      { label: "Wattage", value: "12W" },
      { label: "Input Voltage", value: "220-240V" },
      { label: "Body", value: "Polycarbonate" },
      { label: "Diffuser", value: "Polycarbonate" },
      { label: "Mounting", value: "Wall Mount" },
      { label: "Colour", value: "Black" },
      { label: "Product Size (L × W × H)", value: "169mm x 67mm x 169mm" },
      { label: "Product Weight", value: "0,65kg" },
    ],
    features: [],
    applications: ["Outdoor walls","Facades","Coastal areas"],
    imageUrl: "/product-images/placeholder-product.svg",
    pdfUrl: "/api/download/datasheet/generated/zod102-round-led-wall",
  },
  {
    slug: "orbit-post-top",
    name: "Orbit Post Top",
    category: "outdoor-architectural",
    supplier: "Pioled",
    summary: "Orbit Post Top — outdoor LED luminaire from PioLED, supplied by LumenX.",
    description: "Orbit Post Top — outdoor LED luminaire from PioLED, supplied by LumenX.",
    specs: [
      { label: "Colour Temperature", value: "3CCT (6000K/4000K/3000K)" },
      { label: "Lumen Output", value: "36W = 4680 Lumens | 48W=6240 Lumens | 60W=7800 Lumens" },
      { label: "CRI", value: "> 80" },
      { label: "Operating Temp", value: "-25~50°C" },
      { label: "LED Chips", value: "Epistar 2835" },
      { label: "Beam Angle", value: "120°" },
      { label: "Wattage", value: "36W/48W/60W" },
      { label: "Power Factor", value: "0.9" },
      { label: "Input Voltage", value: "100-277V" },
      { label: "Surge Protection", value: "10kV" },
      { label: "Dimmable", value: "No" },
      { label: "Housing", value: "Pure Aluminium + PC" },
      { label: "Certifications", value: "CE, EMC, IEC60598" },
    ],
    features: [],
    applications: ["Exterior","Commercial","Municipal"],
    imageUrl: "/product-images/orbit-post-top.png",
    pdfUrl: "/api/download/datasheet/generated/orbit-post-top",
  },
  {
    slug: "vista-post-top",
    name: "Vista Post Top",
    category: "outdoor-architectural",
    supplier: "Pioled",
    summary: "Vista Post Top — outdoor LED luminaire from PioLED, supplied by LumenX.",
    description: "Vista Post Top — outdoor LED luminaire from PioLED, supplied by LumenX.",
    specs: [
      { label: "Colour Temperature", value: "3CCT (3000K/4000K/6000K)" },
      { label: "Lumen Output", value: "20W = 2 600lm | 35W = 4 540lm" },
      { label: "CRI", value: ">80" },
      { label: "Operating Temp", value: "-20~40°C" },
      { label: "LED Chips", value: "SMD 2835" },
      { label: "Beam Angle", value: "120°" },
      { label: "Wattage", value: "20/35W" },
      { label: "Input Voltage", value: "170-265V" },
      { label: "Dimmable", value: "No" },
      { label: "Housing", value: "Aluminum" },
      { label: "Certifications", value: "CE" },
    ],
    features: [],
    applications: ["Exterior","Commercial","Municipal"],
    imageUrl: "/product-images/vista-post-top.png",
    pdfUrl: "/api/download/datasheet/generated/vista-post-top",
  },
];