import { Product, ProductCategory } from './types';

/**
 * LumenX product catalogue — the single source of truth.
 * Mirrors the product list in /public/product-list, grouped into the
 * 11 commercial ranges LumenX supplies across South Africa.
 */

/* ── Shared imagery (local assets + themed fallbacks) ── */
const IMG = {
  bulkheadPC: '/product-images/PC_BLUKHEAD.png',
  bulkheadALU: '/product-images/ALU_BLUKHEAD.png',
  downlight: '/product-images/Aegeon_Downlight.png',
  surface: '/product-images/9w_Surface_downlight.png',
  linear: '/product-images/Linear_50x83mm.png',
  highbay: '/product-images/V200_Highbay.png',
  thermisto: '/product-images/Thermisto.png',
  lf55: '/product-images/LF55x80.png',
  triproof: '/product-images/48W_3_CCT_Triproof.png',
  saxa: '/product-images/Saxa_Triproof.png',
  panel: '/product-images/Recessed_Panel.png',
  flood: '/product-images/Performance_Floods.png',
  strip: '/product-images/COB_STRIP.png',
  track: '/product-images/35W_Track_Spot.png',
  // illustrative / installation imagery
  office: '/installation-images/modern-office-cove-lighting.jpeg',
  industrial: '/installation-images/industrial-warehouse-led-lighting.jpeg',
  retail: '/installation-images/retail-track-lighting.png',
  facade: '/installation-images/triangular-facade-accent-lighting.jpeg',
  cove: '/installation-images/shopping-mall-cove-lighting.jpeg',
  pendant: '/installation-images/linear-pendant-office-lighting.jpeg',
};

/* ── Categories ── */
export const PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    id: 'bulkheads',
    title: 'Bulkheads',
    description:
      'Robust wall and ceiling luminaires for corridors, stairwells, entrances and wet areas. Impact-resistant housings with IP ratings for indoor and outdoor use.',
    applications: 'Corridors, stairwells, entrances, plant rooms and exterior walkways',
    imageUrl: '/installation-images/commercial-facade-slat-lighting.jpeg',
    linkLabel: 'Explore Bulkheads',
  },
  {
    id: 'downlights',
    title: 'Downlights',
    description:
      'Recessed and surface downlights delivering precise, comfortable illumination — from trimless architectural details to high-output commercial fittings.',
    applications: 'Offices, retail, hospitality, healthcare and residential interiors',
    imageUrl: '/installation-images/modern-office-cove-lighting.jpeg',
    linkLabel: 'Explore Downlights',
  },
  {
    id: 'floods',
    title: 'Floodlights',
    description:
      'High-output exterior luminaires for area lighting, security, facades and perimeters with asymmetric and symmetric beam options.',
    applications: 'Facades, sports facilities, yards, perimeters and area lighting',
    imageUrl: '/installation-images/triangular-facade-accent-lighting.jpeg',
    linkLabel: 'Explore Floodlights',
  },
  {
    id: 'highbays',
    title: 'Highbays',
    description:
      'High-output luminaires engineered for high ceilings, racking aisles and demanding industrial environments with industry-leading guarantees.',
    applications: 'Warehouses, factories, logistics and manufacturing facilities',
    imageUrl: '/installation-images/industrial-warehouse-led-lighting.jpeg',
    linkLabel: 'Explore Highbays',
  },
  {
    id: 'linears',
    title: 'Linear Lighting',
    description:
      'Continuous, seamless and profile linear systems for architectural, retail and workspace environments — surface, suspended or recessed.',
    applications: 'Offices, retail, education and architectural interiors',
    imageUrl: '/installation-images/linear-pendant-office-lighting.jpeg',
    linkLabel: 'Explore Linear Lighting',
  },
  {
    id: 'panels',
    title: 'Panels',
    description:
      'Low-glare, flicker-free LED panels for clean general illumination across offices, education and healthcare environments.',
    applications: 'Offices, education, healthcare and corporate interiors',
    imageUrl: '/installation-images/open-ceiling-office-lighting.jpeg',
    linkLabel: 'Explore Panels',
  },
  {
    id: 'sensors',
    title: 'Sensors & Controls',
    description:
      'Presence detectors, motion detectors, light sensors and remote controls that optimise energy performance and occupant comfort.',
    applications: 'Commercial buildings, industrial facilities and managed estates',
    imageUrl: '/installation-images/shopping-mall-cove-lighting.jpeg',
    linkLabel: 'Explore Sensors & Controls',
  },
  {
    id: 'solar',
    title: 'Solar Lighting',
    description:
      'Off-grid solar LED lighting solutions for exterior and rural applications where mains power is unavailable or uneconomical.',
    applications: 'Roads, public spaces, parks and off-grid exterior areas',
    imageUrl: '/installation-images/triangular-facade-accent-lighting.jpeg',
    linkLabel: 'Explore Solar Lighting',
  },
  {
    id: 'strips',
    title: 'LED Strips',
    description:
      'Flexible and COB dotless strip lighting for seamless cove, display, under-cabinet and joinery accent illumination.',
    applications: 'Cove lighting, display shelving, signage and joinery accent',
    imageUrl: '/installation-images/shopping-mall-cove-lighting.jpeg',
    linkLabel: 'Explore LED Strips',
  },
  {
    id: 'track',
    title: 'Track Lighting',
    description:
      'Adjustable track spots and linear track fittings for retail, gallery and display applications with precise aiming control.',
    applications: 'Retail, galleries, showrooms and hospitality displays',
    imageUrl: '/installation-images/retail-track-lighting.png',
    linkLabel: 'Explore Track Lighting',
  },
  {
    id: 'vapourproof',
    title: 'Vapour Proof',
    description:
      'Sealed IP65/IP66 luminaires resistant to dust, moisture and vapour for demanding industrial, parking and washdown environments.',
    applications: 'Parking structures, food processing, warehousing and washdown areas',
    imageUrl: '/installation-images/industrial-warehouse-led-lighting.jpeg',
    linkLabel: 'Explore Vapour Proof Lighting',
  },
];

/* ── Products ── */
export const PRODUCTS: Product[] = [
  /* ══════════════════════ BULKHEADS ══════════════════════ */
  {
    slug: 'rhea',
    name: 'Rhea',
    category: 'bulkheads',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/products/rhea-bulkhead',
    summary: 'Integrated surface-mount bulkhead built on OrbitX Direct Drive technology with a rust-free polycarbonate housing.',
    description:
      'The Rhea is a compact integrated LED bulkhead engineered around OrbitX Direct Drive technology — no external driver, no metal and no glass. Its 1mm extruded polycarbonate housing eliminates corrosion risk and breakage, making it a good fit for corridors, stairwells and utility areas where durability and low maintenance matter. Type A light quality (LRC, New York) gives accurate, comfortable colour rendering with immediate full-brightness switching.',
    specs: [
      { label: 'Wattage', value: '15W' },
      { label: 'Efficacy', value: '135 lm/W' },
      { label: 'CCT', value: '5000K (options available)' },
      { label: 'CRI', value: '83 (GAI 96)' },
      { label: 'Beam Angle', value: '160°' },
      { label: 'IP Rating', value: 'IP54' },
      { label: 'Voltage', value: '220–240V AC (operational from 150V)' },
      { label: 'Power Factor', value: '> 0.98' },
      { label: 'Surge Protection', value: '1.5kV' },
      { label: 'Nominal Lifetime', value: 'L70 60,000 hrs' },
      { label: 'Guarantee', value: '6 years operational' },
    ],
    features: [
      'Direct Drive — no external driver required',
      'No-metal, no-glass polycarbonate housing',
      '80% flicker-free (OHS/MHS compliant)',
      'Optional battery backup: 1,000lm for 4 hours',
      'Fire rated UL-94 V2',
    ],
    applications: ['Corridors', 'Stairwells', 'Plant rooms', 'Utility areas'],
    imageUrl: IMG.bulkheadPC,
    warranty: '6-year operational guarantee (24/7)',
  },
  {
    slug: 'phoebe',
    name: 'Phoebe',
    category: 'bulkheads',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/products/phoebe-bulkhead',
    summary: 'IP65 integrated bulkhead for outdoor and wet locations with Type A light quality and an 8-year guarantee.',
    description:
      'The Phoebe extends the Direct Drive bulkhead family to exterior and wet environments with an IP65 rating. The same rust-free polycarbonate construction protects against corrosion and breakage, while Type A light quality maintains accurate colour and visual comfort. Suitable for entrances, under-cover walkways and exterior circulation where weather resistance is required.',
    specs: [
      { label: 'Wattage', value: '15W' },
      { label: 'Efficacy', value: '113 lm/W' },
      { label: 'CCT', value: '5000K (options available)' },
      { label: 'CRI', value: '83 (GAI 96)' },
      { label: 'Beam Angle', value: '160°' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'Voltage', value: '220–240V AC (operational from 150V)' },
      { label: 'Power Factor', value: '> 0.98' },
      { label: 'Surge Protection', value: '1.5kV' },
      { label: 'Nominal Lifetime', value: 'L70 70,000 hrs' },
      { label: 'Guarantee', value: '8 years operational' },
    ],
    features: [
      'IP65 rated for outdoor and wet locations',
      'Rust-free, breakage-resistant polycarbonate housing',
      'Optional radar motion sensor with programmable settings',
      'Optional day/night sensor',
      '8-year operational guarantee (24/7)',
    ],
    applications: ['Exterior entrances', 'Under-cover walkways', 'Wet areas', 'External circulation'],
    imageUrl: IMG.bulkheadALU,
    warranty: '8-year operational guarantee (24/7)',
  },
  {
    slug: 'retrofit',
    name: 'Retrofit',
    category: 'bulkheads',
    supplier: 'OrbitX',
    summary: 'Direct Drive retrofit bulkhead designed to replace existing fittings with minimal rework and maximum energy saving.',
    description:
      'The OrbitX Retrofit bulkhead brings Direct Drive technology to existing installations, replacing older light sources with an integrated, driverless LED solution. Its compact footprint and polycarbonate construction make it a low-maintenance upgrade path for corridors, stairwells and utility spaces where refurbishment efficiency is a priority.',
    specs: [
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Housing', value: 'Polycarbonate (no metal / no glass)' },
      { label: 'Light Quality', value: 'Type A compliant' },
      { label: 'Voltage', value: '220–240V AC' },
      { label: 'Surge Protection', value: '1.5kV' },
      { label: 'Flicker', value: '80% flicker-free' },
    ],
    features: [
      'Driverless Direct Drive design',
      'Low-maintenance, rust-free construction',
      'Fast retrofit of existing fittings',
      'Immediate full-brightness switching',
    ],
    applications: ['Refurbishment projects', 'Corridors', 'Stairwells', 'Utility areas'],
    imageUrl: IMG.bulkheadPC,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'hero',
    name: 'Hero',
    category: 'bulkheads',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product/hero-all-in-one-bulkhead/',
    summary: 'All-in-one IP65 bulkhead with selectable wattage and 3CCT in a round or square polycarbonate housing.',
    description:
      "Pioled's Hero is an all-in-one IP65 bulkhead offering selectable wattage (12W / 18W / 24W) and three colour temperatures (3000K / 4000K / 6000K) in a single fitting — reducing stockholding and simplifying specification. Available in black or white and round or square formats, it pairs a Sanan LED platform with a flicker-free driver for dependable exterior and interior circulation lighting.",
    specs: [
      { label: 'Wattage', value: '12W / 18W / 24W (selectable)' },
      { label: 'Efficacy', value: '105 lm/W' },
      { label: 'CCT', value: '3CCT (3000K / 4000K / 6000K)' },
      { label: 'CRI', value: '> 80' },
      { label: 'Beam', value: '140°' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'IK Rating', value: 'IK08' },
      { label: 'Voltage', value: '185–265V AC' },
      { label: 'LED Chips', value: 'Sanan 2835' },
      { label: 'Surge Protection', value: '1kV' },
    ],
    features: [
      'Selectable wattage and CCT in one fitting',
      'Round or square, black or white options',
      'Flicker-free driver',
      'CE & RoHS certified',
    ],
    applications: ['Exterior walls', 'Corridors', 'Entrances', 'Stairwells'],
    imageUrl: IMG.bulkheadPC,
    warranty: '5-year warranty',
  },
  {
    slug: 'bunker',
    name: 'Bunker',
    category: 'bulkheads',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/exterior-led-lighting/exterior-led-lighting-bulkheads/bunker-die-cast-aluminium-bulkhead-exterior-led-lighting-bulkheads/bunker-ip65-4cct-aluminium-bulkhead-bunker-die-cast-aluminium-bulkhead-exterior-led-lighting-bulkheads/',
    summary: 'Die-cast aluminium IP65 bulkhead with 4CCT selectable colour temperature for robust exterior applications.',
    description:
      'The Bunker is a die-cast aluminium IP65 bulkhead engineered for exterior and semi-exterior environments. Its 4CCT switch provides four selectable colour temperatures, while the aluminium body dissipates heat and resists impact better than polycarbonate alternatives. A tamper-resistant construction suits public and semi-public installations.',
    specs: [
      { label: 'CCT', value: '4CCT selectable' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'Housing', value: 'Die-cast aluminium' },
      { label: 'Mounting', value: 'Wall / Ceiling surface' },
    ],
    features: [
      '4CCT selectable colour temperature',
      'Die-cast aluminium for thermal performance',
      'Impact-resistant construction',
      'Suitable for public and semi-public areas',
    ],
    applications: ['Exterior walls', 'Entrances', 'Underground parking', 'Stairwells'],
    imageUrl: IMG.bulkheadALU,
    warranty: 'Pioled manufacturer warranty',
  },

  /* ══════════════════════ DOWNLIGHTS ══════════════════════ */
  {
    slug: 'aegeon',
    name: 'Aegeon',
    category: 'downlights',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-aegeon-downlight',
    summary: 'Diffused recessed LED downlight with low-glare output and passive die-cast cooling.',
    description:
      "Rubicon's Aegeon is a diffused recessed downlight designed for efficiency and visual comfort. A die-cast aluminium housing doubles as the heatsink for fully passive cooling, while the diffused optic produces soft, low-glare illumination. It is an ideal general-lighting workhorse for offices, retail and healthcare environments.",
    specs: [
      { label: 'Wattage', value: '12W – 24W' },
      { label: 'Lumens', value: '1,440lm – 2,880lm' },
      { label: 'IP Rating', value: 'IP20 / IP44' },
      { label: 'CRI', value: '90+' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Beam Angle', value: '90°' },
      { label: 'Cutout', value: 'Ø68 – Ø205mm' },
      { label: 'Lifetime', value: 'L80B10 > 50,000 hrs' },
    ],
    features: [
      'Diffused, low-glare light distribution',
      'Passive die-cast cooling — no moving parts',
      'High CRI 90+ for accurate colour',
      'Flicker-free operation',
    ],
    applications: ['Corporate offices', 'Healthcare', 'Education', 'High-end retail'],
    imageUrl: IMG.downlight,
    pdfUrl: '/datasheets/LumenX_Datasheet_Aegeon Downlight.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'lean-153',
    name: 'Lean 153',
    category: 'downlights',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-aegeon-downlight',
    summary: 'Compact, low-profile recessed downlight from the Aegeon family for discreet ceiling integration.',
    description:
      'The Lean 153 is a low-profile recessed downlight within Rubicon\u2019s Aegeon range, engineered for shallow ceiling voids and discreet architectural integration. It shares the diffused, low-glare optic and passive cooling approach of the family while accommodating tighter installation constraints.',
    specs: [
      { label: 'Type', value: 'Recessed, low-profile' },
      { label: 'Optics', value: 'Diffused, low-glare' },
      { label: 'Cooling', value: 'Passive die-cast' },
      { label: 'CRI', value: '90+' },
      { label: 'CCT', value: '3000K / 4000K' },
    ],
    features: [
      'Shallow ceiling void compatible',
      'Low-glare diffused output',
      'Discreet architectural profile',
    ],
    applications: ['Offices', 'Retail', 'Healthcare', 'Corridors'],
    imageUrl: IMG.downlight,
    pdfUrl: '/datasheets/LumenX_Datasheet_Aegeon Downlight.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'cob-dr',
    name: 'COB-DR',
    category: 'downlights',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/cob-dr/',
    summary: 'Round COB recessed downlight range from 7W to 35W with deep-recessed reflector optics.',
    description:
      "LEDwise's COB-DR is a round COB recessed downlight delivering high lumen output and deep-recessed glare control from a compact die-cast aluminium housing. Available from 7W to 35W with multiple beam angles, CRI80 or CRI90 and a choice of non-dim, phase-dim or DALI control.",
    specs: [
      { label: 'Wattage', value: '7.2W – 36.5W' },
      { label: 'Lumens', value: '855lm – 4,519lm' },
      { label: 'Beam Angle', value: '25° / 30° / 45° / 50°' },
      { label: 'CRI', value: '80 / 90' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Cutout', value: 'Ø85 / Ø115 / Ø140mm' },
      { label: 'IP Rating', value: 'IP20' },
      { label: 'Control', value: 'Non-dim / Phase-dim / DALI' },
      { label: 'Housing', value: 'Die-cast aluminium' },
    ],
    features: [
      'Deep-recessed reflector for glare control',
      'CRI90 option for accurate colour',
      'DALI and phase-dimming options',
      'Assembled in South Africa',
    ],
    applications: ['Retail', 'Offices', 'Hospitality', 'Display lighting'],
    imageUrl: IMG.downlight,
    warranty: '5-year warranty',
  },
  {
    slug: 'x-tf8',
    name: 'X-TF8',
    category: 'downlights',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/x-tf8/',
    summary: 'Trimless reflector downlight with fixed and swivel trim variants and <3 SDCM colour consistency.',
    description:
      "The X-TF8 is a trimless reflector downlight available in fixed and swivel trims for architectural installations. A high-pressure die-cast aluminium housing with powder-coated finish gives clean, precise light, with a <3 SDCM colour consistency and optional CRI90, emergency and Bluetooth variants.",
    specs: [
      { label: 'Wattage', value: '7.2W – 13.9W' },
      { label: 'Lumens', value: '694lm – 1,364lm' },
      { label: 'Beam Angle', value: '38° / 60°' },
      { label: 'CRI', value: '80 (90 on request)' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Cutout', value: 'Ø70mm' },
      { label: 'IP Rating', value: 'IP20' },
      { label: 'Colour Consistency', value: '< 3 SDCM' },
      { label: 'Control', value: 'Non-dim / Phase / DALI / Bluetooth' },
    ],
    features: [
      'Fixed and swivel trim variants',
      'Trimless architectural finish',
      'Optional emergency version (1 hour)',
      'Optional Bluetooth control',
    ],
    applications: ['Architectural interiors', 'Offices', 'Retail', 'Hospitality'],
    imageUrl: IMG.downlight,
    warranty: '5-year warranty',
  },
  {
    slug: 'cob-r-sq1',
    name: 'COB-R-SQ1',
    category: 'downlights',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/cob-r-sq1/',
    summary: 'Square swivel COB recessed downlight from 10W to 45W with specialty colour options.',
    description:
      "The COB-R-SQ1 is a square swivel COB recessed downlight offering adjustable aiming within a single-module cutout. Rated from 10W to 45W, it supports specialty retail, food and health colour temperatures alongside standard 3000K / 4000K, with DALI and Bluetooth control options for flexible lighting scenes.",
    specs: [
      { label: 'Wattage', value: '10.1W – 42W' },
      { label: 'Lumens', value: '1,268lm – 4,846lm' },
      { label: 'Beam Angle', value: '15° / 30° / 45° / 60°' },
      { label: 'CRI', value: '80 / 90 (95+ on request)' },
      { label: 'CCT', value: '3000K / 4000K + specialty' },
      { label: 'Cutout', value: '158 × 158mm' },
      { label: 'IP Rating', value: 'IP20' },
      { label: 'Control', value: 'Non-dim / DALI / Bluetooth' },
    ],
    features: [
      'Swivel trim for adjustable aiming',
      'Specialty retail / food / health colours',
      'CRI95+ available',
      'DALI and Bluetooth control',
    ],
    applications: ['Retail', 'Display', 'Hospitality', 'Food retail'],
    imageUrl: IMG.downlight,
    warranty: '5-year warranty',
  },
  {
    slug: 'cob-r-sq2',
    name: 'COB-R-SQ2',
    category: 'downlights',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/cob-r-sq2/',
    summary: 'Double-module square swivel COB recessed downlight for higher output from 20W to 84W.',
    description:
      'The COB-R-SQ2 is the double-module version of the COB-R square swivel downlight, providing roughly twice the output in a 360mm-wide fitting for larger retail and commercial spaces. It retains the swivel trim, specialty colour options and DALI / Bluetooth control of the single-module range.',
    specs: [
      { label: 'Wattage', value: '20.2W – 84.4W' },
      { label: 'Lumens', value: '2×1,268lm – 2×4,846lm' },
      { label: 'Beam Angle', value: '15° / 30° / 45° / 60°' },
      { label: 'CRI', value: '80 / 90 (95+ on request)' },
      { label: 'CCT', value: '3000K / 4000K + specialty' },
      { label: 'Cutout', value: '305 × 158mm' },
      { label: 'IP Rating', value: 'IP20' },
      { label: 'Control', value: 'Non-dim / DALI / Bluetooth' },
    ],
    features: [
      'Double-module high output',
      'Swivel trim per module',
      'Specialty colour options',
      'DALI and Bluetooth control',
    ],
    applications: ['Large retail', 'Showrooms', 'Commercial', 'Display'],
    imageUrl: IMG.downlight,
    warranty: '5-year warranty',
  },
  {
    slug: 'cob-r-sq3',
    name: 'COB-R-SQ3',
    category: 'downlights',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/cob-r-sq3/',
    summary: 'Triple-module square swivel COB recessed downlight for high-output architectural applications.',
    description:
      'The COB-R-SQ3 is the triple-module flagship of the COB-R square swivel downlight range, delivering maximum output for large open-plan retail and commercial spaces. Swivel trims, specialty colours and full control flexibility make it a powerful architectural accent tool.',
    specs: [
      { label: 'Type', value: 'Triple-module square swivel' },
      { label: 'Beam Angle', value: '15° / 30° / 45° / 60°' },
      { label: 'CRI', value: '80 / 90 (95+ on request)' },
      { label: 'CCT', value: '3000K / 4000K + specialty' },
      { label: 'IP Rating', value: 'IP20' },
      { label: 'Control', value: 'Non-dim / DALI / Bluetooth' },
    ],
    features: [
      'Triple-module maximum output',
      'Per-module swivel aiming',
      'Specialty colour options',
      'DALI and Bluetooth control',
    ],
    applications: ['Large retail', 'Atriums', 'Showrooms', 'Commercial spaces'],
    imageUrl: IMG.downlight,
    warranty: '5-year warranty',
  },
  {
    slug: 'sauron',
    name: 'Sauron',
    category: 'downlights',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product/25-20-18-16w-sauron-3cct-led-round-downlight/',
    summary: '3CCT round COB downlight from 16W to 25W with UGR<19 and Bridgelux LED chips.',
    description:
      "Pioled's Sauron is a high-performance round COB downlight available from 16W to 25W with UGR<19 for low-glare comfort. Bridgelux COB LEDs, a 3CCT switch, 3kV surge protection and an optional dimmable driver make it a versatile commercial recessed solution.",
    specs: [
      { label: 'Wattage', value: '16W / 18W / 20W / 25W' },
      { label: 'Lumens', value: '1,920lm – 3,000lm' },
      { label: 'CCT', value: '3CCT (3000K / 4000K / 6000K)' },
      { label: 'CRI', value: '> 80' },
      { label: 'UGR', value: '< 19' },
      { label: 'Beam', value: '45°' },
      { label: 'LED Chips', value: 'Bridgelux COB' },
      { label: 'Voltage', value: '200–277V AC' },
      { label: 'Surge Protection', value: '3kV' },
      { label: 'Dimming', value: 'Optional dimmable driver' },
    ],
    features: [
      'UGR<19 low-glare comfort',
      'Bridgelux COB LED platform',
      'Flicker-free AGT driver',
      '3kV surge protection',
    ],
    applications: ['Offices', 'Retail', 'Healthcare', 'Commercial interiors'],
    imageUrl: IMG.downlight,
    warranty: '5-year warranty',
  },
  {
    slug: 'legend',
    name: 'Legend',
    category: 'downlights',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/high-powered-downlights-interior-led-lighting/legend-3cct-round-downlights/',
    summary: 'High-powered 3CCT round downlight range for demanding commercial applications.',
    description:
      "Pioled's Legend series comprises high-powered round downlights with 3CCT switching, engineered for commercial spaces that require higher output from a standard recessed format. The range balances lumen performance with colour flexibility for flexible specification.",
    specs: [
      { label: 'CCT', value: '3CCT selectable' },
      { label: 'Type', value: 'High-powered round downlight' },
      { label: 'Housing', value: 'Aluminium' },
      { label: 'IP Rating', value: 'IP20' },
    ],
    features: [
      'High-power output',
      '3CCT selectable colour temperature',
      'Aluminium construction',
    ],
    applications: ['Commercial', 'Retail', 'Offices', 'Hospitality'],
    imageUrl: IMG.downlight,
    warranty: 'Pioled manufacturer warranty',
  },
  {
    slug: 'gu10',
    name: 'GU10',
    category: 'downlights',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/gu10-fixtures-and-accessories-interior-led-lighting/',
    summary: 'GU10 fixtures and accessories for flexible lamp-based accent and downlighting.',
    description:
      'Pioled\u2019s GU10 range covers fixtures and accessories built around the universal GU10 lamp format, providing a simple, serviceable solution for accent and downlighting applications where lamp replacement flexibility is required.',
    specs: [
      { label: 'Lamp Base', value: 'GU10' },
      { label: 'Type', value: 'Fixture & accessories' },
      { label: 'IP Rating', value: 'IP20' },
    ],
    features: [
      'Universal GU10 lamp compatibility',
      'Simple, serviceable design',
      'Accent and downlighting applications',
    ],
    applications: ['Residential', 'Retail', 'Hospitality', 'Display'],
    imageUrl: IMG.surface,
    warranty: 'Pioled manufacturer warranty',
  },
  {
    slug: 'pakman',
    name: 'Pakman',
    category: 'downlights',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/tiltable-downlighters/pakman-round-tilt-downlighter/',
    summary: '3CCT tiltable round downlighter for adjustable accent and general lighting.',
    description:
      'The Pakman is a 3CCT tiltable round downlighter that combines adjustable aiming with colour-temperature flexibility. Its IP20 rating and tilt mechanism make it suited to accent lighting and general illumination where direction needs to be fine-tuned after installation.',
    specs: [
      { label: 'CCT', value: '3CCT selectable' },
      { label: 'Type', value: 'Tiltable round downlighter' },
      { label: 'IP Rating', value: 'IP20' },
    ],
    features: [
      'Tiltable head for adjustable aiming',
      '3CCT colour temperature selection',
      'Accent and general lighting',
    ],
    applications: ['Retail', 'Hospitality', 'Accent lighting', 'Offices'],
    imageUrl: IMG.downlight,
    warranty: 'Pioled manufacturer warranty',
  },
  {
    slug: 'mario',
    name: 'Mario',
    category: 'downlights',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product/35w-mario-round-tilt-led-downlighter/',
    summary: '35W round-tilt IP40 downlighter for uniform spot, decorative and soft lighting in one fitting.',
    description:
      "Pioled's 35W Mario is a round-tilt IP40 downlighter delivering spot, decorative and soft lighting from a single recessed fitting. Its beautiful recessed design integrates into ceilings in homes, offices, retail stores, supermarkets, exhibition centres and restaurants.",
    specs: [
      { label: 'Wattage', value: '35W' },
      { label: 'IP Rating', value: 'IP40' },
      { label: 'Type', value: 'Round tilt downlighter' },
    ],
    features: [
      'Spot, decorative and soft lighting in one',
      'Round-tilt adjustable aiming',
      'Recessed architectural design',
    ],
    applications: ['Retail stores', 'Supermarkets', 'Exhibition centres', 'Restaurants'],
    imageUrl: IMG.downlight,
    warranty: 'Pioled manufacturer warranty',
  },

  /* ══════════════════════ FLOODLIGHTS ══════════════════════ */
  {
    slug: 'flood',
    name: 'Flood',
    category: 'floods',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/pdfs/OrbitX-Floodlight-small.pdf',
    summary: 'OrbitX Direct Drive floodlight for exterior area, facade and perimeter lighting.',
    description:
      "OrbitX's Direct Drive floodlight provides dependable exterior light for facades, yards and perimeter security. Built on the same driverless Direct Drive platform as the wider OrbitX range, it offers robust, weather-resistant performance with immediate full-brightness switching and a low-maintenance design.",
    specs: [
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Application', value: 'Exterior area / facade / perimeter' },
      { label: 'Switching', value: 'Immediate full brightness' },
    ],
    features: [
      'Driverless Direct Drive design',
      'Weather-resistant exterior construction',
      'Low-maintenance operation',
      'Immediate full-brightness switching',
    ],
    applications: ['Facades', 'Perimeter security', 'Yards', 'Area lighting'],
    imageUrl: IMG.flood,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'performance',
    name: 'Performance',
    category: 'floods',
    supplier: 'LEDVANCE',
    summary: 'High-power floodlight series from 10W to 175W with asymmetric and symmetric beams.',
    description:
      "The Performance floodlight series spans 10W to 175W for area lighting, sports facilities and security perimeters. Asymmetric and symmetric beam options suit a broad range of exterior applications, with an adjustable steel bracket and robust IP65 construction for long-term outdoor performance.",
    specs: [
      { label: 'Wattage', value: '10W – 175W' },
      { label: 'Lumens', value: '1,250lm – 22,500lm' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'CRI', value: '70+ (80 option)' },
      { label: 'CCT', value: '4000K / 5000K' },
      { label: 'Beam', value: 'Asymmetric / Symmetric' },
      { label: 'Mounting', value: 'Adjustable steel bracket' },
      { label: 'Lifetime', value: 'L90B10 > 100,000 hrs' },
    ],
    features: [
      'Wide 10W–175W output range',
      'Asymmetric and symmetric distributions',
      'Adjustable mounting bracket',
      'Long L90B10 lifetime',
    ],
    applications: ['Sports fields', 'Harbour berths', 'Mining yards', 'Perimeter security'],
    imageUrl: IMG.flood,
    pdfUrl: '/datasheets/LumenX_Datasheet_Performance Floods.pdf',
    warranty: 'LEDVANCE manufacturer warranty',
  },

  /* ══════════════════════ HIGHBAYS ══════════════════════ */
  {
    slug: 'jupiter',
    name: 'Jupiter',
    category: 'highbays',
    supplier: 'OrbitX',
    summary: 'OrbitX Direct Drive highbay for high-ceiling industrial environments with maximum output.',
    description:
      "The Jupiter is OrbitX's Direct Drive highbay, engineered for high-ceiling warehouses, factories and logistics facilities. The driverless platform removes a key failure point while delivering high lumen output and Type A light quality for demanding industrial applications.",
    specs: [
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Application', value: 'High-ceiling industrial' },
      { label: 'Light Quality', value: 'Type A compliant' },
    ],
    features: [
      'Driverless Direct Drive design',
      'High lumen output for high ceilings',
      'Type A light quality',
      'Low-maintenance operation',
    ],
    applications: ['Warehouses', 'Factories', 'Logistics', 'Manufacturing'],
    imageUrl: IMG.highbay,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'ace-hp',
    name: 'ACE',
    category: 'highbays',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/ace-hp-s/',
    summary: 'ACE-HP-S high-power linear highbay from 75W to 206W with aisle and oval optics.',
    description:
      "LEDwise's ACE-HP-S is a high-power linear highbay delivering up to 25,000+ lumens across lengths from 1140mm to 2260mm. Purpose-designed optics — including oval, aisle-symmetric and aisle-asymmetric distributions — make it a strong fit for racking aisles, production lines and high-ceiling industrial spaces.",
    specs: [
      { label: 'Wattage', value: '75W – 206W' },
      { label: 'Lumens', value: '8,809lm – 25,487lm+' },
      { label: 'Lengths', value: '1140 / 1700 / 2260mm' },
      { label: 'Beam', value: '60° / 90° / Oval / Aisle Asym / Aisle Sym' },
      { label: 'CRI', value: '80' },
      { label: 'CCT', value: '3000K / 4000K / 5000K' },
      { label: 'Control', value: 'Non-dim / DALI' },
    ],
    features: [
      'High-power output to 206W',
      'Aisle and oval optic options',
      'Multiple lengths for layout flexibility',
      'DALI dimming available',
    ],
    applications: ['Racking aisles', 'Production lines', 'Distribution centres', 'Factories'],
    imageUrl: IMG.highbay,
    warranty: '5-year warranty',
  },
  {
    slug: 'umgeni',
    name: 'Umgeni',
    category: 'highbays',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-umgeni-linear-highbay',
    summary: 'High-performance linear highbay delivering over 35,000 lumens with excellent thermal design.',
    description:
      "Rubicon's Umgeni is a high-performance linear highbay delivering in excess of 35,000 lumens for warehouses, factories and logistics hubs. Excellent thermal design supports sustained output and long life, and it is manufactured locally in South Africa.",
    specs: [
      { label: 'Output', value: '> 35,000 lm' },
      { label: 'Type', value: 'Linear highbay' },
      { label: 'Cooling', value: 'Excellent thermal design' },
      { label: 'Manufacture', value: 'Locally manufactured' },
    ],
    features: [
      'High output exceeding 35,000 lumens',
      'Optimised thermal management',
      'Locally manufactured',
    ],
    applications: ['Warehouses', 'Factories', 'Logistics hubs', 'Industrial'],
    imageUrl: IMG.highbay,
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'thermisto',
    name: 'Thermisto',
    category: 'highbays',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/themisto-lensed',
    summary: 'Lensed linear highbay with controlled illumination and multiple mounting options.',
    description:
      "Rubicon's Themisto lensed LED linear gives controlled light with multiple mounting options. Its lensed optic manages distribution for racking and workspace applications, while the wide wattage range and excellent thermal management suit warehouses, workshops and retail spaces.",
    specs: [
      { label: 'Wattage', value: '17W – 100W' },
      { label: 'Lumens', value: '2,300lm – 12,000lm' },
      { label: 'IP Rating', value: 'IP40' },
      { label: 'CRI', value: '80+' },
      { label: 'CCT', value: '4000K / 5000K' },
      { label: 'Profile', value: '55×80mm extruded' },
      { label: 'Mounting', value: 'Suspended / Surface' },
      { label: 'Lifetime', value: 'L80B10 > 60,000 hrs' },
    ],
    features: [
      'Lensed optic for controlled distribution',
      'Multiple mounting options',
      'Wide wattage range',
      'Excellent thermal management',
    ],
    applications: ['Warehouse racking', 'Production lines', 'Workshops', 'Retail spaces'],
    imageUrl: IMG.thermisto,
    pdfUrl: '/datasheets/LumenX_Datasheet_Thermisto.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'delta',
    name: 'Delta',
    category: 'highbays',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product/240w-padel-delta-3cct-linear-ip65-highbay-sq/',
    summary: '240W linear IP65 highbay delivering 40,800 lumens with 3CCT switching.',
    description:
      "Pioled's 240W Delta is a high-output linear IP65 highbay delivering 40,800 lumens for demanding industrial and high-ceiling applications. Lumileds 3030 LED chips, 6kV surge protection, IK09 impact rating and a 3CCT switch make it a robust, flexible solution for challenging environments.",
    specs: [
      { label: 'Wattage', value: '240W' },
      { label: 'Lumens', value: '40,800lm' },
      { label: 'CCT', value: '3CCT (incl. 5700K)' },
      { label: 'CRI', value: '> 80' },
      { label: 'Beam', value: '90°' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'IK Rating', value: 'IK09' },
      { label: 'LED Chips', value: 'Lumileds 3030' },
      { label: 'Surge Protection', value: '6kV' },
      { label: 'Dimming', value: 'Yes' },
    ],
    features: [
      'Very high 40,800lm output',
      'IP65 + IK09 durability',
      '6kV surge protection',
      'Mounting bracket included',
    ],
    applications: ['High-ceiling industrial', 'Warehouses', 'Manufacturing', 'Logistics'],
    imageUrl: IMG.highbay,
    warranty: '5-year warranty',
  },
  {
    slug: 'raptor',
    name: 'Raptor',
    category: 'highbays',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/led-highbays/raptor-3-in-1-ufo-highbay/',
    summary: 'IP65 3-in-1 UFO highbay with selectable wattage and CCT for flexible specification.',
    description:
      "Pioled's Raptor is an IP65 UFO highbay with 3-in-1 functionality — selectable wattage and colour temperature in a single fitting. The round UFO form factor suits high-ceiling industrial and warehouse spaces where wide, even illumination is required.",
    specs: [
      { label: 'Type', value: 'UFO highbay, 3-in-1' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'CCT', value: 'Selectable' },
      { label: 'Wattage', value: 'Selectable' },
    ],
    features: [
      '3-in-1 selectable wattage and CCT',
      'IP65 rated',
      'UFO form factor for wide distribution',
    ],
    applications: ['Warehouses', 'Factories', 'Workshops', 'High-ceiling spaces'],
    imageUrl: IMG.highbay,
    warranty: 'Pioled manufacturer warranty',
  },

  /* ══════════════════════ LINEAR LIGHTING ══════════════════════ */
  {
    slug: 'puck-seamless',
    name: 'Puck Seamless',
    category: 'linears',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/products/puck-seamless',
    summary: 'Integrated seamless linear with a <3mm end-cap line for continuous runs, in 1200mm and 2400mm.',
    description:
      "OrbitX's Puck Seamless is an integrated linear LED light with a thin (<3mm) end-cap line for a near-continuous look when mounted end-to-end. Available in 1200mm and 2400mm lengths, it pairs Direct Drive technology with Type A light quality for architectural and workspace applications.",
    specs: [
      { label: 'Power', value: '58W (1200mm) / 116W (2400mm)' },
      { label: 'Efficacy', value: '110 lm/W' },
      { label: 'CCT', value: '4000K / 5000K' },
      { label: 'CRI', value: '83 (GAI 96)' },
      { label: 'Beam Angle', value: '160°' },
      { label: 'Lengths', value: '1200mm / 2400mm' },
      { label: 'Voltage', value: '220–240V AC' },
      { label: 'Lifetime', value: 'L70 60,000 hrs' },
      { label: 'Guarantee', value: '6 years operational' },
    ],
    features: [
      '<3mm end-cap line for seamless runs',
      'Direct Drive — no external driver',
      'Type A light quality',
      'Surface / suspended mounting',
    ],
    applications: ['Offices', 'Retail', 'Workspaces', 'Architectural interiors'],
    imageUrl: IMG.linear,
    warranty: '6-year operational guarantee (24/7)',
  },
  {
    slug: 'puck-profile-70x36',
    name: 'Puck Profile 70x36',
    category: 'linears',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/pdfs/OrbitX-Puck-Profile-70x36-specifications.pdf',
    summary: '70×36mm Puck profile linear system for recessed, surface and suspended applications.',
    description:
      "The Puck Profile 70×36 is a versatile linear profile system from OrbitX's Puck range. Its 70×36mm profile supports a range of mounting styles, making it suitable for architectural and commercial applications where a larger, higher-output linear form is required.",
    specs: [
      { label: 'Profile', value: '70×36mm' },
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Mounting', value: 'Recessed / Surface / Suspended' },
    ],
    features: [
      '70×36mm linear profile',
      'Multiple mounting options',
      'Direct Drive technology',
    ],
    applications: ['Architectural interiors', 'Offices', 'Retail', 'Commercial'],
    imageUrl: IMG.linear,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'puck-profile-40x43',
    name: 'Puck Profile 40x43',
    category: 'linears',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/pdfs/OrbitX-Puck-Profile-40x43-specifications.pdf',
    summary: '40×43mm Puck profile linear system for compact architectural runs.',
    description:
      "The Puck Profile 40×43 is a compact linear profile from OrbitX's Puck range. Its 40×43mm form suits narrower architectural details and continuous runs where a slim, discreet profile is preferred.",
    specs: [
      { label: 'Profile', value: '40×43mm' },
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Mounting', value: 'Surface / Suspended / Recessed' },
    ],
    features: [
      'Compact 40×43mm profile',
      'Slim, discreet appearance',
      'Direct Drive technology',
    ],
    applications: ['Architectural interiors', 'Offices', 'Retail', 'Cove lighting'],
    imageUrl: IMG.linear,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'kepler',
    name: 'Kepler',
    category: 'linears',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/pdfs/OrbitX-Kepler-specifications.pdf',
    summary: 'OrbitX Kepler linear system for continuous architectural illumination.',
    description:
      "The Kepler is an OrbitX linear lighting system designed for continuous architectural and commercial illumination. Direct Drive technology and clean continuous-run capability make it well suited to offices, retail and workspace environments where seamless lines of light are part of the design intent.",
    specs: [
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Type', value: 'Continuous linear system' },
      { label: 'Light Quality', value: 'Type A compliant' },
    ],
    features: [
      'Continuous seamless runs',
      'Direct Drive technology',
      'Type A light quality',
    ],
    applications: ['Offices', 'Retail', 'Workspaces', 'Architectural interiors'],
    imageUrl: IMG.linear,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'lds-5083',
    name: 'LDS5083',
    category: 'linears',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/lds-5083/',
    summary: '50×83mm linear profile available as single or continuous runs with 30–50W/m output.',
    description:
      "LEDwise's LDS-5083 is a 50×83mm linear profile offered as single (S) or continuous (C) runs at 30W, 40W or 50W per metre. Available in lengths from 580mm to 1980mm and finishes including white, black, aluminium and custom, it suits both standalone and continuous architectural applications.",
    specs: [
      { label: 'Profile', value: '50×83mm' },
      { label: 'Wattage', value: '16W – 78W (30/40/50 W/m)' },
      { label: 'Lumens', value: '1,316lm – 6,000lm+' },
      { label: 'Lengths', value: '580 – 1980mm' },
      { label: 'CRI', value: '80 / 90' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Finishes', value: 'White / Black / Aluminium / Custom' },
      { label: 'Control', value: 'Non-dim / DALI' },
    ],
    features: [
      'Single and continuous run options',
      'Three wattages per metre',
      'Multiple finishes',
      'DALI dimming available',
    ],
    applications: ['Offices', 'Retail', 'Architectural interiors', 'Workspaces'],
    imageUrl: IMG.linear,
    pdfUrl: '/datasheets/LumenX_Datasheet_Linear 50x83mm.pdf',
    warranty: '5-year warranty',
  },
  {
    slug: 'ldr-6563',
    name: 'LDR6563',
    category: 'linears',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/ldr-6563/',
    summary: '65×63mm linear profile for higher-output continuous and single applications.',
    description:
      "The LDR-6563 is a 65×63mm linear profile from LEDwise, offering higher output for larger architectural and commercial spaces. Available in single and continuous configurations at 30–50W/m across lengths from 580mm to 2260mm.",
    specs: [
      { label: 'Profile', value: '65×63mm' },
      { label: 'Wattage', value: '15.5W – 78W (30/40/50 W/m)' },
      { label: 'Lumens', value: '1,257lm – 6,000lm+' },
      { label: 'Lengths', value: '580 – 2260mm' },
      { label: 'CRI', value: '80' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Finishes', value: 'White / Black / Aluminium / Custom' },
    ],
    features: [
      'Higher-output 65×63mm profile',
      'Single and continuous configurations',
      'Long run capability to 2260mm',
    ],
    applications: ['Offices', 'Retail', 'Commercial', 'Architectural interiors'],
    imageUrl: IMG.linear,
    warranty: '5-year warranty',
  },
  {
    slug: 'lrd-9063',
    name: 'LRD9063',
    category: 'linears',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/ldr-9063-c/',
    summary: '90×63mm large-format linear profile for high-output architectural runs.',
    description:
      "The LRD-9063 is LEDwise's large-format 90×63mm linear profile, designed for high-output architectural applications where a substantial linear presence and maximum lumen delivery are required. Continuous-run capability supports long, uninterrupted lines of light.",
    specs: [
      { label: 'Profile', value: '90×63mm' },
      { label: 'Type', value: 'Large-format linear, continuous' },
      { label: 'CRI', value: '80' },
      { label: 'CCT', value: '3000K / 4000K' },
    ],
    features: [
      'Large 90×63mm profile',
      'High-output continuous runs',
      'Architectural presence',
    ],
    applications: ['Atriums', 'Large offices', 'Commercial', 'Architectural interiors'],
    imageUrl: IMG.linear,
    warranty: '5-year warranty',
  },
  {
    slug: 'base',
    name: 'BASE',
    category: 'linears',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/bace/',
    summary: 'BACE base linear profile offering 135 lm/W efficacy in single or continuous form.',
    description:
      "LEDwise's BACE (BASE) linear reaches up to 135 lm/W in a clean, efficient profile. Available as single or continuous runs at 30–50W/m, it is a cost-effective architectural linear for offices, retail and general commercial spaces.",
    specs: [
      { label: 'Wattage', value: '16W – 54W (30/40/50 W/m)' },
      { label: 'Lumens', value: '2,400lm – 6,682lm' },
      { label: 'Efficacy', value: 'Up to 135 lm/W' },
      { label: 'Lengths', value: '580 – 1420mm' },
      { label: 'CRI', value: '80' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Control', value: 'Non-dim / DALI' },
    ],
    features: [
      'High 135 lm/W efficacy',
      'Single and continuous options',
      'Cost-effective architectural linear',
    ],
    applications: ['Offices', 'Retail', 'Commercial', 'Workspaces'],
    imageUrl: IMG.linear,
    warranty: '5-year warranty',
  },
  {
    slug: 'ace-linear',
    name: 'ACE',
    category: 'linears',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/ace/',
    summary: 'ACE linear with aisle and oval optics for task-oriented commercial illumination.',
    description:
      "The ACE linear from LEDwise combines high output with a choice of optics — including oval, aisle-symmetric and aisle-asymmetric — for task-oriented commercial and industrial applications. Available as single or continuous runs at 30–50W/m.",
    specs: [
      { label: 'Wattage', value: '16W – 54W (30/40/50 W/m)' },
      { label: 'Lumens', value: '2,439lm – 6,717lm' },
      { label: 'Beam', value: '60° / 90° / Oval / Aisle Asym / Aisle Sym' },
      { label: 'Lengths', value: '580 – 1420mm' },
      { label: 'CRI', value: '80' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Control', value: 'Non-dim / DALI' },
    ],
    features: [
      'Aisle and oval optic options',
      'Single and continuous runs',
      'Task-oriented distribution',
    ],
    applications: ['Racking aisles', 'Retail', 'Offices', 'Workspaces'],
    imageUrl: IMG.linear,
    warranty: '5-year warranty',
  },
  {
    slug: 'protega-gen-2',
    name: 'Protega Gen 2',
    category: 'linears',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/protega-gen2',
    summary: 'LED linear luminaire delivering up to 171 lm/W in a sleek, easily maintained profile.',
    description:
      "Rubicon's Protega Gen2 LED linear reaches up to 171 lm/W in a sleek, easily maintained profile. Designed for retail, commercial and industrial spaces, it balances outstanding efficacy with clean aesthetics and practical maintenance access.",
    specs: [
      { label: 'Efficacy', value: 'Up to 171 lm/W' },
      { label: 'Type', value: 'Linear luminaire' },
      { label: 'Maintenance', value: 'Easily maintained profile' },
    ],
    features: [
      'Industry-leading 171 lm/W efficacy',
      'Sleek architectural profile',
      'Easy maintenance access',
      'Retail, commercial and industrial',
    ],
    applications: ['Retail', 'Commercial', 'Industrial', 'Workspaces'],
    imageUrl: IMG.linear,
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'lf40',
    name: 'LF40',
    category: 'linears',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/light-frame-40',
    summary: 'Light Frame 40 diffused linear for standalone and continuous, surface, suspended or recessed use.',
    description:
      "Rubicon's Light Frame 40 is a versatile diffused linear suitable for both standalone and continuous applications. With surface, suspended and recessed mounting options, it showcases lighting as part of the environment in larger modern spaces.",
    specs: [
      { label: 'Profile', value: 'Light Frame 40' },
      { label: 'Type', value: 'Diffused linear' },
      { label: 'Mounting', value: 'Surface / Suspended / Recessed' },
    ],
    features: [
      'Standalone and continuous applications',
      'Three mounting options',
      'Diffused, comfortable output',
    ],
    applications: ['Modern offices', 'Retail', 'Reception areas', 'Atriums'],
    imageUrl: IMG.linear,
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'lf20',
    name: 'LF20',
    category: 'linears',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-light-frame-20-linear',
    summary: 'Narrow 20mm diffused linear for task lighting in modern environments.',
    description:
      "Rubicon's Light Frame 20 is a narrow 20mm diffused LED linear for task lighting in modern environments. Its slim profile suits surface and suspended mounting where a discreet, refined linear detail is required.",
    specs: [
      { label: 'Profile', value: '20mm narrow' },
      { label: 'Type', value: 'Diffused linear' },
      { label: 'Mounting', value: 'Surface / Suspended' },
    ],
    features: [
      'Narrow 20mm profile',
      'Discreet, refined detail',
      'Task-oriented lighting',
    ],
    applications: ['Modern offices', 'Task lighting', 'Retail', 'Workspaces'],
    imageUrl: IMG.linear,
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'lf55',
    name: 'LF55',
    category: 'linears',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/light-frame-family-55-55x80-80',
    summary: '55×80mm Light Frame family linear for high-output industrial and commercial use.',
    description:
      "The LF55 (Light Frame Family 55 / 55×80) is a high-output linear profile from Rubicon's Light Frame family. Its 55×80mm extruded body supports high lumen output and excellent thermal management for industrial and commercial environments.",
    specs: [
      { label: 'Profile', value: '55×80mm extruded' },
      { label: 'Wattage', value: '17W – 100W' },
      { label: 'Lumens', value: '2,300lm – 12,000lm' },
      { label: 'IP Rating', value: 'IP40' },
      { label: 'CRI', value: '80+' },
      { label: 'CCT', value: '4000K / 5000K' },
      { label: 'Mounting', value: 'Suspended / Surface' },
      { label: 'Lifetime', value: 'L80B10 > 60,000 hrs' },
    ],
    features: [
      'High-output 55×80mm profile',
      'Excellent thermal management',
      'Surface and suspended mounting',
    ],
    applications: ['Warehouse racking', 'Production lines', 'Industrial', 'Workspaces'],
    imageUrl: IMG.lf55,
    pdfUrl: '/datasheets/LumenX_Datasheet_LF55x80.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'thermisto',
    name: 'Thermisto',
    category: 'linears',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/themisto-lensed',
    summary: 'Lensed LED linear delivering controlled illumination with multiple mounting options.',
    description:
      "Rubicon's Themisto lensed LED linear gives controlled light with multiple mounting options. Its lensed optic manages distribution for both workspace and display applications, while the wide wattage range and excellent thermal management make it equally at home in warehouses, workshops and retail spaces.",
    specs: [
      { label: 'Wattage', value: '17W – 100W' },
      { label: 'Lumens', value: '2,300lm – 12,000lm' },
      { label: 'IP Rating', value: 'IP40' },
      { label: 'CRI', value: '80+' },
      { label: 'CCT', value: '4000K / 5000K' },
      { label: 'Profile', value: '55×80mm extruded' },
      { label: 'Mounting', value: 'Suspended / Surface' },
      { label: 'Lifetime', value: 'L80B10 > 60,000 hrs' },
    ],
    features: [
      'Lensed optic for controlled distribution',
      'Multiple mounting options',
      'Wide wattage range',
      'Excellent thermal management',
    ],
    applications: ['Warehouses', 'Workshops', 'Retail spaces', 'Racking aisles'],
    imageUrl: IMG.thermisto,
    pdfUrl: '/datasheets/LumenX_Datasheet_Thermisto.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'soniq',
    name: 'Soniq',
    category: 'linears',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/linear-lights-interior-led-lighting/soniq-3-wattage-seamless-linkable-linear-lights-linear-lights-interior-led-lighting-interior-led-lighting/soniq-3-wattage-seamless-linkable-linear-lights-linear-lights-interior-led-lighting/',
    summary: '3-wattage seamless linkable linear for continuous runs with flexible output.',
    description:
      "Pioled's Soniq is a 3-wattage seamless linkable linear light that allows continuous runs with selectable output. Its seamless linking and three wattage options make it a natural fit for offices, retail and architectural environments that need long, uninterrupted lines of light.",
    specs: [
      { label: 'Wattage', value: '3 selectable wattages' },
      { label: 'Type', value: 'Seamless linkable linear' },
      { label: 'Linking', value: 'Seamless end-to-end' },
    ],
    features: [
      'Seamless linkable design',
      'Three selectable wattages',
      'Continuous run capability',
    ],
    applications: ['Offices', 'Retail', 'Architectural interiors', 'Cove lighting'],
    imageUrl: IMG.linear,
    warranty: 'Pioled manufacturer warranty',
  },

  /* ══════════════════════ PANELS ══════════════════════ */
  {
    slug: 'puck-panel',
    name: 'Puck Panel',
    category: 'panels',
    supplier: 'OrbitX',
    summary: 'OrbitX Direct Drive panel for clean, efficient general illumination.',
    description:
      "The OrbitX Puck Panel brings Direct Drive technology to the panel format, providing clean, efficient general illumination for offices and commercial spaces. The driverless design removes a key failure point while maintaining Type A light quality and low-maintenance operation.",
    specs: [
      { label: 'Technology', value: 'OrbitX Direct Drive' },
      { label: 'Type', value: 'LED panel' },
      { label: 'Light Quality', value: 'Type A compliant' },
    ],
    features: [
      'Driverless Direct Drive design',
      'Clean, uniform panel output',
      'Low-maintenance operation',
    ],
    applications: ['Offices', 'Commercial', 'Education', 'Healthcare'],
    imageUrl: IMG.panel,
    warranty: 'OrbitX Direct Drive guarantee',
  },
  {
    slug: 'veris',
    name: 'Veris',
    category: 'panels',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-veris-panel',
    summary: 'Back-lit low-glare LED panel with UGR<19 and flicker-free operation.',
    description:
      "Rubicon's Veris is a back-lit LED panel delivering low-glare (UGR<19) general lighting with a clean finish. Flicker-free operation makes it a good choice for offices, education and hospitals where visual comfort and screen use matter.",
    specs: [
      { label: 'UGR', value: '< 19' },
      { label: 'Type', value: 'Back-lit LED panel' },
      { label: 'Flicker', value: 'Flicker-free' },
      { label: 'Finish', value: 'Clean finish' },
    ],
    features: [
      'Low-glare UGR<19 output',
      'Back-lit, flicker-free',
      'Clean architectural finish',
    ],
    applications: ['Offices', 'Education', 'Hospitals', 'Corporate interiors'],
    imageUrl: IMG.panel,
    pdfUrl: '/datasheets/LumenX_Datasheet_Recessed Panel.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'dark-light',
    name: 'Dark Light',
    category: 'panels',
    supplier: 'Mez',
    summary: 'Dark-light panel with deeply recessed optics for glare-free architectural illumination.',
    description:
      "The Mez Dark Light panel uses deeply recessed 'dark light' optics to virtually eliminate visible glare, delivering crisp, controlled illumination for premium architectural and workplace environments where visual comfort is paramount.",
    specs: [
      { label: 'Type', value: 'Dark-light panel' },
      { label: 'Optics', value: 'Deep-recessed, low-glare' },
    ],
    features: [
      'Deep-recessed dark-light optics',
      'Glare-free illumination',
      'Premium architectural finish',
    ],
    applications: ['Premium offices', 'Boardrooms', 'Hospitality', 'Architectural interiors'],
    imageUrl: IMG.panel,
    warranty: 'Mez manufacturer warranty',
  },

  /* ══════════════════════ SENSORS & CONTROLS ══════════════════════ */
  {
    slug: 'is-2360-r',
    name: 'IS 2360 R',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/motion-detectors/indoor-detectors/is-2360-de-eco-8m-csid-32073.html',
    summary: 'Indoor motion detector with 8m reach for automatic lighting control.',
    description:
      "Steinel's IS 2360 R is an indoor passive-infrared motion detector offering an 8m detection range for automatic lighting control in corridors, offices and utility areas. It slips into the background and detects every movement for reliable energy-saving switching.",
    specs: [
      { label: 'Type', value: 'PIR motion detector' },
      { label: 'Range', value: '8m' },
      { label: 'Application', value: 'Indoor' },
    ],
    features: [
      'Reliable passive-infrared detection',
      '8m detection range',
      'Automatic lighting control',
    ],
    applications: ['Corridors', 'Offices', 'Utility areas', 'Stairwells'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'is-2360-s',
    name: 'IS 2360 S',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/motion-detectors/indoor-detectors/is-2360-eco-7m-006556.html',
    summary: 'ECO indoor motion detector with 7m reach for energy-efficient switching.',
    description:
      "The IS 2360 S (ECO 7m) is Steinel's energy-efficient indoor motion detector with a 7m reach. Designed to slip into the background and detect every movement, it is an economical solution for automatic lighting in interior circulation and utility spaces.",
    specs: [
      { label: 'Type', value: 'PIR motion detector' },
      { label: 'Range', value: '7m' },
      { label: 'Application', value: 'Indoor (ECO)' },
    ],
    features: [
      'Energy-efficient ECO series',
      '7m detection range',
      'Discreet design',
    ],
    applications: ['Corridors', 'Offices', 'Stairwells', 'Utility areas'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'light-sensor',
    name: 'Light Sensor',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/smart-extensions/photoelectric-lighting-controller/light-sensor-dual-058326.html',
    summary: 'Photoelectric lighting controller measuring daylight for constant-light control.',
    description:
      "Steinel's Light Sensor Dual is a photoelectric lighting controller that measures ambient daylight to enable constant-light control. Concealed and square in format, it integrates with lighting systems to automatically maintain target illuminance and reduce energy consumption.",
    specs: [
      { label: 'Type', value: 'Photoelectric lighting controller' },
      { label: 'Function', value: 'Constant-light control' },
      { label: 'Mounting', value: 'Concealed, square' },
    ],
    features: [
      'Daylight-dependent control',
      'Constant-light regulation',
      'Concealed square format',
    ],
    applications: ['Daylit offices', 'Constant-light control', 'Commercial buildings', 'Atriums'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'dualtech',
    name: 'DualTech',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/presence-detectors/ultrasonic/dualtech-007997.html',
    summary: 'Ultrasonic presence detector combining the best of two detection technologies.',
    description:
      "Steinel's DualTech COM1 is an ultrasonic presence detector that combines passive-infrared and ultrasonic technologies in one device — the best of both worlds for reliable presence detection in offices and meeting rooms, even where movement is subtle.",
    specs: [
      { label: 'Type', value: 'Ultrasonic presence detector' },
      { label: 'Technology', value: 'Dual (PIR + ultrasonic)' },
      { label: 'Wiring', value: 'Concealed (COM1)' },
    ],
    features: [
      'Dual detection technology',
      'Reliable presence detection',
      'Concealed wiring',
    ],
    applications: ['Offices', 'Meeting rooms', 'Classrooms', 'Presence-based control'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'is-3360',
    name: 'IS 3360',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/presence-detectors/passive-infrared/is-3360-079659.html',
    summary: 'Round in-ceiling presence detector with all-round vision for offices.',
    description:
      "The IS 3360 COM1 is a round, in-ceiling passive-infrared presence detector with far-sightedness and all-round vision. It is designed for presence-based lighting control in offices and commercial interiors where discreet ceiling integration is required.",
    specs: [
      { label: 'Type', value: 'PIR presence detector' },
      { label: 'Mounting', value: 'In-ceiling, round' },
      { label: 'Coverage', value: 'All-round detection' },
    ],
    features: [
      'All-round detection coverage',
      'Discreet in-ceiling mounting',
      'Presence-based control',
    ],
    applications: ['Offices', 'Commercial interiors', 'Meeting rooms', 'Presence detection'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'is-3360-highbay',
    name: 'IS 3360 Highbay',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/motion-detectors/indoor-detectors/is-3360-mx-highbay-033569.html',
    summary: 'Surface-mount highbay motion detector with powerful reach for industrial ceilings.',
    description:
      "Steinel's IS 3360 MX Highbay is a square, surface-mounted motion detector with a head for heights — delivering powerful reach and reliable detection for high-ceiling industrial and warehouse environments.",
    specs: [
      { label: 'Type', value: 'Motion detector (highbay)' },
      { label: 'Mounting', value: 'Surface, square' },
      { label: 'Application', value: 'High-ceiling industrial' },
    ],
    features: [
      'Powerful reach for high ceilings',
      'Reliable industrial detection',
      'Square surface-mount format',
    ],
    applications: ['Warehouses', 'High-ceiling industrial', 'Logistics', 'Motion control'],
    imageUrl: IMG.industrial,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'is-345-highbay',
    name: 'IS 345 Highbay',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/motion-detectors/indoor-detectors/is-345-mx-highbay-010492.html',
    summary: 'Specialist high-bay motion detector for the highest level of surveillance quality.',
    description:
      "The IS 345 MX Highbay is Steinel's specialist motion detector for high-bay warehouses, delivering the highest level of surveillance quality. Its surface-mount square format and powerful reach make it the go-to for demanding high-ceiling industrial detection.",
    specs: [
      { label: 'Type', value: 'Motion detector (highbay)' },
      { label: 'Mounting', value: 'Surface, square' },
      { label: 'Application', value: 'High-bay warehouses' },
    ],
    features: [
      'Specialist for high-bay warehouses',
      'Highest surveillance quality',
      'Powerful detection reach',
    ],
    applications: ['High-bay warehouses', 'Distribution centres', 'Industrial', 'Motion control'],
    imageUrl: IMG.industrial,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'dual-hf-corridor',
    name: 'Dual HF Corridoor',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/presence-detectors/high-frequency/dual-hf-002978.html',
    summary: 'High-frequency corridor presence detector that points the way.',
    description:
      "Steinel's Dual HF COM1 is a high-frequency presence detector purpose-built for corridors — a corridor sensor that points the way in both technology and design. High-frequency detection provides reliable presence sensing through partitions and along circulation routes.",
    specs: [
      { label: 'Type', value: 'High-frequency presence detector' },
      { label: 'Application', value: 'Corridors' },
      { label: 'Wiring', value: 'Concealed (COM1)' },
    ],
    features: [
      'High-frequency detection',
      'Purpose-built for corridors',
      'Concealed wiring',
    ],
    applications: ['Corridors', 'Circulation routes', 'Offices', 'Presence control'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'hf-360',
    name: 'HF 360',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/presence-detectors/high-frequency/hf-360-079512.html',
    summary: 'In-ceiling high-frequency presence detector — hardly visible, sees everything.',
    description:
      "Steinel's HF 360 COM1 is an in-ceiling high-frequency presence detector you can hardly see, but which sees everything. 360° high-frequency coverage makes it well suited to open-plan offices and rooms needing discreet presence detection.",
    specs: [
      { label: 'Type', value: 'High-frequency presence detector' },
      { label: 'Mounting', value: 'In-ceiling' },
      { label: 'Coverage', value: '360°' },
    ],
    features: [
      '360° high-frequency coverage',
      'Discreet in-ceiling design',
      'Reliable presence detection',
    ],
    applications: ['Open-plan offices', 'Meeting rooms', 'Commercial', 'Presence control'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'is-2180',
    name: 'IS 2180',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/motion-detectors/indoor-detectors/is-2180-eco-034702.html',
    summary: 'ECO wall-mount motion detector that cuts a fine figure on the wall.',
    description:
      "Steinel's IS 2180 ECO is a wall-mounted passive-infrared motion detector that cuts a fine figure on the wall while acting as a reliable guard dog for automatic lighting. Its ECO design focuses on energy efficiency for interior circulation and utility spaces.",
    specs: [
      { label: 'Type', value: 'PIR motion detector' },
      { label: 'Mounting', value: 'Wall' },
      { label: 'Application', value: 'Indoor (ECO)' },
    ],
    features: [
      'Wall-mount design',
      'Energy-efficient ECO series',
      'Reliable motion detection',
    ],
    applications: ['Corridors', 'Stairwells', 'Utility areas', 'Motion control'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'ir-quattro-micro',
    name: 'IR Quattro Micro',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/presence-detectors/passive-infrared/ir-quattro-micro-6m-053789.html',
    summary: 'Small, precise 6m passive-infrared presence detector.',
    description:
      "Steinel's IR Quattro MICRO is a small, precise passive-infrared presence detector with a 6m range. Its compact form makes it well suited to discrete installation in smaller rooms and workspaces.",
    specs: [
      { label: 'Type', value: 'PIR presence detector' },
      { label: 'Range', value: '6m' },
      { label: 'Mounting', value: 'In-ceiling' },
    ],
    features: [
      'Small, precise form factor',
      '6m detection range',
      'Discreet in-ceiling mounting',
    ],
    applications: ['Small offices', 'Workspaces', 'Meeting rooms', 'Presence detection'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'ir-quattro-hd',
    name: 'IR Quattro HD',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/presence-detectors/passive-infrared/ir-quattro-hd-24m-002794.html',
    summary: '24m high-density passive-infrared presence detector for large spaces.',
    description:
      "Steinel's IR Quattro HD is a high-density passive-infrared presence detector with a 24m range — it fits on the ceiling and sees what others dream of. High-density detection zones make it well suited to large open spaces, atriums and halls.",
    specs: [
      { label: 'Type', value: 'PIR presence detector' },
      { label: 'Range', value: '24m' },
      { label: 'Detection', value: 'High-density zones' },
    ],
    features: [
      '24m detection range',
      'High-density detection zones',
      'Well suited to large spaces',
    ],
    applications: ['Atriums', 'Large offices', 'Halls', 'Presence detection'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'sens-iq-s',
    name: 'Sens IQ S',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/motion-detectors/outdoor-detectors/sensiq-s-059613.html',
    summary: 'Outdoor motion detector with compact design, also available with KNX.',
    description:
      "Steinel's sensIQ S is an outdoor motion detector offering the perfect reference — a compact design with precise detection, also available with KNX integration. It suits exterior lighting control around buildings and outdoor areas.",
    specs: [
      { label: 'Type', value: 'Outdoor motion detector' },
      { label: 'Design', value: 'Compact' },
      { label: 'Integration', value: 'KNX option' },
    ],
    features: [
      'Compact outdoor design',
      'Precise exterior detection',
      'KNX integration available',
    ],
    applications: ['Building exteriors', 'Outdoor areas', 'Perimeter', 'Exterior control'],
    imageUrl: IMG.facade,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'smart-remote',
    name: 'Smart Remote',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/lighting/accessories-spare-parts/remote-controls/remote-control-smart-remote-009151.html',
    summary: 'One remote plus app to put you in control of everything.',
    description:
      "Steinel's Smart Remote puts you in control of everything — pairing a physical remote with an app for convenient commissioning and adjustment of Steinel sensors and luminaires. It simplifies configuration across a building's lighting estate.",
    specs: [
      { label: 'Type', value: 'Remote control' },
      { label: 'Control', value: 'Remote + app' },
    ],
    features: [
      'One remote for the whole system',
      'App-based control and configuration',
      'Simplifies commissioning',
    ],
    applications: ['System commissioning', 'Configuration', 'Building management'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },
  {
    slug: 'service-remote',
    name: 'Service Remote',
    category: 'sensors',
    supplier: 'Steinel',
    supplierUrl: 'https://www.steinel.de/en/group/sensors/smart-extensions/accessories/service-remote-control-rc8-559410.html',
    summary: 'IR service remote control RC8 for commissioning and servicing sensors.',
    description:
      "The Steinel Service Remote RC8 is an IR remote control for commissioning and servicing Steinel sensors. It provides convenient access to settings and adjustments during installation and maintenance without requiring physical access to mounted detectors.",
    specs: [
      { label: 'Type', value: 'IR service remote' },
      { label: 'Model', value: 'RC8' },
    ],
    features: [
      'IR control for commissioning',
      'Convenient sensor adjustment',
      'Supports installation and servicing',
    ],
    applications: ['Commissioning', 'Servicing', 'Sensor configuration'],
    imageUrl: IMG.office,
    warranty: 'Steinel Professional Line warranty',
  },

  /* ══════════════════════ SOLAR LIGHTING ══════════════════════ */
  {
    slug: 'sunfor-solar-led',
    name: 'Sunfor Solar LED',
    category: 'solar',
    supplier: 'Sunfor',
    summary: 'Off-grid solar LED lighting solutions for exterior and rural applications.',
    description:
      "Sunfor's solar LED lighting range provides off-grid illumination for roads, public spaces, parks and rural areas where mains power is unavailable or uneconomical. Integrated photovoltaic panels charge high-efficiency LED luminaires for dependable dusk-to-dawn operation with minimal infrastructure.",
    specs: [
      { label: 'Type', value: 'Off-grid solar LED' },
      { label: 'Power', value: 'Solar photovoltaic' },
      { label: 'Operation', value: 'Dusk-to-dawn' },
    ],
    features: [
      'Fully off-grid operation',
      'No mains infrastructure required',
      'Dusk-to-dawn automatic operation',
    ],
    applications: ['Roads', 'Public spaces', 'Parks', 'Rural areas'],
    imageUrl: IMG.facade,
    warranty: 'Sunfor manufacturer warranty',
  },

  /* ══════════════════════ LED STRIPS ══════════════════════ */
  {
    slug: 'cob-strip-orbitx',
    name: 'COB',
    category: 'strips',
    supplier: 'OrbitX',
    summary: 'Chip-on-board dotless LED strip for seamless, continuous linear light.',
    description:
      "OrbitX's COB strip gives continuous, dot-free light using chip-on-board technology. High-density COB LEDs produce seamless illumination that suits architectural cove, display and joinery work where individual LED points would be visible.",
    specs: [
      { label: 'Type', value: 'COB (Chip-on-Board)' },
      { label: 'Voltage', value: '24V DC' },
      { label: 'CRI', value: '90+' },
    ],
    features: [
      'Dot-free continuous light',
      'High CRI 90+',
      'Seamless architectural detail',
    ],
    applications: ['Cove lighting', 'Display shelving', 'Joinery accent', 'Under-cabinet'],
    imageUrl: IMG.strip,
    pdfUrl: '/datasheets/LumenX_Datasheet_COB STRIP.pdf',
    warranty: 'OrbitX manufacturer warranty',
  },
  {
    slug: 'cob-strip-pioled',
    name: 'COB',
    category: 'strips',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product/10w-24v-cob-dotless-strip/',
    summary: '5/10W 24V IP20 COB dotless strip (8mm) with 5cm cutting points.',
    description:
      "Pioled's 5/10W 24V COB dotless strip gives seamless, dot-free light in a slim 8mm profile. With a 5cm cutting point, up to 5m series installation without voltage drop, and CRI>90, it suits cove, display and joinery accent lighting.",
    specs: [
      { label: 'Wattage', value: '5W / 10W' },
      { label: 'Lumens', value: '> 500lm / 1,100lm' },
      { label: 'IP Rating', value: 'IP20' },
      { label: 'CRI', value: '> 90' },
      { label: 'CCT', value: '3000K / 4000K / 6000K' },
      { label: 'Voltage', value: '24V DC' },
      { label: 'Beam', value: '180°' },
      { label: 'Cutting Point', value: '5cm' },
      { label: 'Dimming', value: '0–24V dimmable' },
    ],
    features: [
      'Dotless COB for seamless light',
      '5cm cutting points',
      'Up to 5m series with no voltage drop',
      'CRI>90 accurate colour',
    ],
    applications: ['Cove lighting', 'Display shelving', 'Under-cabinet', 'Joinery accent'],
    imageUrl: IMG.strip,
    pdfUrl: '/datasheets/LumenX_Datasheet_COB STRIP.pdf',
    warranty: '3-year warranty',
  },

  /* ══════════════════════ TRACK LIGHTING ══════════════════════ */
  {
    slug: 'standard',
    name: 'Standard',
    category: 'track',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-standard-track-light',
    summary: 'Compact LED track light with adjustable beam and special colour options.',
    description:
      "Rubicon's Standard track light is a compact LED track fitting delivering powerful, consistent illumination for retail and commercial spaces. Adjustable beam and special colour options provide the flexibility needed for effective product and display lighting.",
    specs: [
      { label: 'Type', value: 'LED track light' },
      { label: 'Beam', value: 'Adjustable' },
      { label: 'Colours', value: 'Special options available' },
    ],
    features: [
      'Compact, consistent output',
      'Adjustable beam',
      'Special colour options',
    ],
    applications: ['Retail', 'Commercial', 'Display', 'Galleries'],
    imageUrl: IMG.track,
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'bazuka',
    name: 'Bazuka',
    category: 'track',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/track-lights-interior-led-lighting/bazuka-3-wire-track-surface-mount-spot/',
    summary: '3-wire track / surface mount spot for flexible accent lighting.',
    description:
      "Pioled's Bazuka is a 3-wire track and surface-mount spot offering flexible accent lighting for retail and display applications. Its dual mounting capability — track or direct surface — simplifies specification across different ceiling types.",
    specs: [
      { label: 'Type', value: '3-wire track / surface spot' },
      { label: 'Mounting', value: 'Track / Surface' },
    ],
    features: [
      'Track and surface mounting',
      '3-wire track compatibility',
      'Adjustable spot aiming',
    ],
    applications: ['Retail', 'Display', 'Galleries', 'Accent lighting'],
    imageUrl: IMG.track,
    warranty: 'Pioled manufacturer warranty',
  },
  {
    slug: 'blaster',
    name: 'Blaster',
    category: 'track',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product/35-30-28w-blaster-3-wire-track-spot-light/',
    summary: '35/30/28W 3-wire track spot with 340° rotation and CRI>90.',
    description:
      "Pioled's Blaster is a high-output 3-wire track spot available in 28W, 30W and 35W with CRI>90 for accurate colour. A 340° rotation mechanism enables precise aiming, which suits retail display and accent work.",
    specs: [
      { label: 'Wattage', value: '28W / 30W / 35W' },
      { label: 'Lumens', value: '> 3,220lm – 4,025lm' },
      { label: 'CCT', value: '3CCT (3000K / 4000K / 6000K)' },
      { label: 'CRI', value: '> 90' },
      { label: 'Beam', value: '36°' },
      { label: 'Rotation', value: '340°' },
      { label: 'IK Rating', value: 'IK05' },
      { label: 'Voltage', value: '200–265V AC' },
      { label: 'Surge Protection', value: '3kV' },
    ],
    features: [
      'CRI>90 accurate colour',
      '340° rotation for aiming',
      'High output to 4,025lm',
      '3kV surge protection',
    ],
    applications: ['Retail', 'Showrooms', 'Galleries', 'Accent lighting'],
    imageUrl: IMG.track,
    warranty: '5-year warranty',
  },
  {
    slug: 'leda',
    name: 'Leda',
    category: 'track',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/track-lights-interior-led-lighting/leda-3wire-track-tilt-ip20-linears-track-lights-interior-led-lighting/',
    summary: '3-wire track tilt IP20 linear for directional linear accent lighting.',
    description:
      "Pioled's Leda is a 3-wire track tilt linear delivering directional linear accent lighting for retail and display environments. Its tiltable linear format provides broader coverage than a spot while retaining precise aiming on a 3-wire track system.",
    specs: [
      { label: 'Type', value: '3-wire track linear' },
      { label: 'Tilt', value: 'Tiltable' },
      { label: 'IP Rating', value: 'IP20' },
    ],
    features: [
      'Tiltable linear format',
      '3-wire track compatibility',
      'Broader accent coverage',
    ],
    applications: ['Retail', 'Display', 'Showrooms', 'Accent lighting'],
    imageUrl: IMG.track,
    warranty: 'Pioled manufacturer warranty',
  },
  {
    slug: 'snypa',
    name: 'Snypa',
    category: 'track',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/track-lights-interior-led-lighting/snypa-track-surface-gu10-fixtures-interior-led-lighting/',
    summary: 'Track / surface GU10 fixtures for flexible lamp-based accent lighting.',
    description:
      "Pioled's Snypa track and surface GU10 fixtures bring lamp-based flexibility to accent lighting. Compatible with universal GU10 lamps, they suit both track and surface mounting for retail, hospitality and display applications.",
    specs: [
      { label: 'Type', value: 'Track / surface GU10 fixture' },
      { label: 'Lamp', value: 'GU10' },
    ],
    features: [
      'GU10 lamp compatibility',
      'Track and surface mounting',
      'Flexible lamp-based accent',
    ],
    applications: ['Retail', 'Hospitality', 'Display', 'Accent lighting'],
    imageUrl: IMG.track,
    warranty: 'Pioled manufacturer warranty',
  },
  {
    slug: '3-4-wire',
    name: '3/4 Wire',
    category: 'track',
    supplier: 'Spazio',
    summary: '3/4-wire track lighting system for flexible, reconfigurable accent illumination.',
    description:
      "Spazio's 3/4-wire track lighting system provides a flexible, reconfigurable platform for accent and display lighting. Supporting both 3-circuit and 4-circuit configurations, it enables independent control of multiple luminaires on a single track for sophisticated retail and gallery schemes.",
    specs: [
      { label: 'Type', value: 'Track lighting system' },
      { label: 'Circuits', value: '3-wire / 4-wire' },
    ],
    features: [
      '3- and 4-circuit configurations',
      'Independent control per circuit',
      'Reconfigurable layout',
    ],
    applications: ['Retail', 'Galleries', 'Showrooms', 'Display lighting'],
    imageUrl: IMG.track,
    warranty: 'Spazio manufacturer warranty',
  },

  /* ══════════════════════ VAPOUR PROOF ══════════════════════ */
  {
    slug: 'neptune',
    name: 'Neptune',
    category: 'vapourproof',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/products/neptune',
    summary: 'IP65 integrated vapour-proof linear with 8-year operational guarantee.',
    description:
      "OrbitX's Neptune is a weather-resistant IP65 integrated linear built on Direct Drive technology. Dust, moisture and vapour proof, it is engineered for demanding environments — with a UL-94 V0 fire rating, Type A light quality and an 8-year operational guarantee.",
    specs: [
      { label: 'Efficacy', value: '135 lm/W' },
      { label: 'CCT', value: '5000K (options available)' },
      { label: 'CRI', value: '83 (GAI 96)' },
      { label: 'Beam Angle', value: '120°' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'Fire Rating', value: 'UL-94 V0' },
      { label: 'Voltage', value: '220–240V AC (from 150V)' },
      { label: 'Surge Protection', value: '1.5kV' },
      { label: 'Lifetime', value: 'L70 70,000 hrs' },
      { label: 'Guarantee', value: '8 years operational' },
    ],
    features: [
      'IP65 dust, moisture and vapour proof',
      'UL-94 V0 fire rating',
      'Direct Drive — no external driver',
      '8-year operational guarantee',
    ],
    applications: ['Parking structures', 'Washdown areas', 'Food processing', 'Industrial'],
    imageUrl: IMG.triproof,
    warranty: '8-year operational guarantee (24/7)',
  },
  {
    slug: 'titan',
    name: 'Titan',
    category: 'vapourproof',
    supplier: 'OrbitX',
    supplierUrl: 'https://www.orbitx.co.za/products/titan',
    summary: 'IP65 integrated vapour-proof linear with UL-94 V0 fire safety.',
    description:
      "OrbitX's Titan is an IP65 integrated linear built for dust, moisture and vapour-proof environments. Direct Drive technology, UL-94 V0 fire safety (no flaming droplets) and Type A light quality make it a dependable choice for demanding industrial applications.",
    specs: [
      { label: 'Efficacy', value: '135 lm/W' },
      { label: 'CCT', value: '5000K (options available)' },
      { label: 'CRI', value: '83 (GAI 96)' },
      { label: 'Beam Angle', value: '120°' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'Fire Rating', value: 'UL-94 V0' },
      { label: 'Voltage', value: '220–240V AC (from 150V)' },
      { label: 'Surge Protection', value: '1.5kV' },
      { label: 'Lifetime', value: 'L70 60,000 hrs' },
      { label: 'Guarantee', value: '6 years operational' },
    ],
    features: [
      'IP65 vapour-proof construction',
      'UL-94 V0 fire safety',
      'Optional battery backup',
      'Optional radar motion sensor',
    ],
    applications: ['Parking structures', 'Industrial', 'Washdown areas', 'Food processing'],
    imageUrl: IMG.triproof,
    warranty: '6-year operational guarantee (24/7)',
  },
  {
    slug: 'saxa',
    name: 'Saxa',
    category: 'vapourproof',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-saxa-triproof',
    summary: 'IP65 tri-proof linear with high performance and emergency backup option.',
    description:
      "Rubicon's Saxa is an IP65 tri-proof LED linear with high performance for indoor and outdoor use. Side or back cable entry and an emergency backup option make it a flexible, robust solution for industrial and parking environments.",
    specs: [
      { label: 'Wattage', value: '18W – 54W' },
      { label: 'Lumens', value: '2,160lm – 6,480lm' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'CRI', value: '80+' },
      { label: 'CCT', value: '4000K / 5000K' },
      { label: 'Cable Entry', value: 'Side or back' },
      { label: 'Emergency', value: 'Backup option' },
      { label: 'Mounting', value: 'Surface / Suspended' },
    ],
    features: [
      'IP65 tri-proof construction',
      'Side or back cable entry',
      'Emergency backup option',
      'High performance output',
    ],
    applications: ['Parking garages', 'Food processing', 'Warehouses', 'Industrial washdown'],
    imageUrl: IMG.saxa,
    pdfUrl: '/datasheets/LumenX_Datasheet_Saxa Triproof.pdf',
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'metropolis',
    name: 'Metropolis',
    category: 'vapourproof',
    supplier: 'Rubicon',
    supplierUrl: 'https://lighting.rubicon.tech/products/rubicon-metropolis-linear',
    summary: 'IP66 vapour-proof linear with chemical resistance and interchangeable gear tray.',
    description:
      "Rubicon's Metropolis is a high-performance vapour-proof LED linear with IP66 protection and chemical resistance. An interchangeable SMD gear tray simplifies maintenance, which suits industrial and commercial environments with harsh conditions.",
    specs: [
      { label: 'IP Rating', value: 'IP66' },
      { label: 'Resistance', value: 'Chemical resistant' },
      { label: 'Gear Tray', value: 'Interchangeable SMD' },
    ],
    features: [
      'IP66 vapour-proof rating',
      'Chemical resistance',
      'Interchangeable SMD gear tray',
    ],
    applications: ['Industrial', 'Commercial', 'Harsh environments', 'Washdown areas'],
    imageUrl: IMG.triproof,
    warranty: 'Rubicon manufacturer warranty',
  },
  {
    slug: 'vp',
    name: 'VP',
    category: 'vapourproof',
    supplier: 'Ledwise',
    supplierUrl: 'https://ledwise.co.za/product/vp/',
    summary: 'IP65 polycarbonate vapour-proof linear with emergency and motion sensor options.',
    description:
      "LEDwise's VP is an IP65 vapour-proof linear in a grey polycarbonate housing. Available at 40W, 50W and 60W with a 110° beam, it supports surface, P2000 and suspended mounting, with optional emergency and microwave motion sensor add-ons.",
    specs: [
      { label: 'Wattage', value: '40W / 50W / 60W' },
      { label: 'Lumens', value: '4,382lm – 6,962lm' },
      { label: 'Beam Angle', value: '110°' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'CRI', value: '80 (90 on request)' },
      { label: 'CCT', value: '3000K / 4000K' },
      { label: 'Housing', value: 'Grey polycarbonate' },
      { label: 'Mounting', value: 'Surface / P2000 / Suspended' },
      { label: 'Control', value: 'Non-dim / DALI' },
    ],
    features: [
      'IP65 vapour-proof polycarbonate',
      'Emergency version available',
      'Optional microwave motion sensor',
      'Multiple mounting options',
    ],
    applications: ['Parking structures', 'Industrial', 'Canopies', 'Utility areas'],
    imageUrl: IMG.triproof,
    warranty: '5-year warranty',
  },
  {
    slug: 'kuda',
    name: 'Kuda',
    category: 'vapourproof',
    supplier: 'Pioled',
    supplierUrl: 'https://pioledlighting.co.za/product-category/interior-led-lighting/linear-lights-interior-led-lighting/ip65-kuda-wattage-selectable-linear-light/',
    summary: 'IP65 wattage-selectable linear for flexible vapour-proof lighting.',
    description:
      "Pioled's Kuda is an IP65 wattage-selectable linear light offering flexible output selection in a vapour-proof format. It suits parking, canopies, industrial corridors and utility spaces where sealed, durable construction and adjustable output are required.",
    specs: [
      { label: 'IP Rating', value: 'IP65' },
      { label: 'Wattage', value: 'Selectable' },
      { label: 'Type', value: 'Vapour-proof linear' },
    ],
    features: [
      'IP65 vapour-proof construction',
      'Selectable wattage',
      'Flexible output specification',
    ],
    applications: ['Parking structures', 'Canopies', 'Industrial corridors', 'Utility areas'],
    imageUrl: IMG.triproof,
    warranty: 'Pioled manufacturer warranty',
  },
];

/** Products grouped by category id (derived). */
export const PRODUCTS_BY_CATEGORY: Record<string, Product[]> = PRODUCTS.reduce(
  (acc, product) => {
    (acc[product.category] ||= []).push(product);
    return acc;
  },
  {} as Record<string, Product[]>,
);

export function getCategory(categoryId: string): ProductCategory | undefined {
  return PRODUCT_CATEGORIES.find((c) => c.id === categoryId);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return PRODUCTS_BY_CATEGORY[categoryId] || [];
}

export function getProduct(categoryId: string, slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.category === categoryId && p.slug === slug);
}

/**
 * Convert a static datasheet path (/datasheets/X.pdf) into the tracked
 * backend download URL so every datasheet download is recorded.
 */
export const datasheetDownloadUrl = (pdfUrl: string): string => {
  const name = pdfUrl.split('/').filter(Boolean).pop() || '';
  return `/api/download/datasheet/${encodeURIComponent(name)}`;
};

/** Flat list of all unique local datasheet downloads. */
export function getAllDatasheets(): { name: string; href: string }[] {
  const seen = new Set<string>();
  const sheets: { name: string; href: string }[] = [];
  PRODUCTS.forEach((p) => {
    if (p.pdfUrl && !seen.has(p.pdfUrl)) {
      seen.add(p.pdfUrl);
      sheets.push({ name: p.name, href: p.pdfUrl });
    }
  });
  return sheets.sort((a, b) => a.name.localeCompare(b.name));
}

/** Complete local datasheet library (LumenX-branded + supplier-linked ranges). */
export const DATASHEET_LIBRARY: { name: string; href: string }[] = [
  { name: '300x1200 Recessed Panel', href: '/datasheets/LumenX_Datasheet_300x1200 Recessed Panel.pdf' },
  { name: '35W Track Spot', href: '/datasheets/LumenX_Datasheet_35W Track Spot.pdf' },
  { name: '48W 3 CCT Triproof', href: '/datasheets/LumenX_Datasheet_48W 3 CCT Triproof.pdf' },
  { name: '60W Street Light', href: '/datasheets/LumenX_Datasheet_60W Street light.pdf' },
  { name: '9W Surface Downlight', href: '/datasheets/LumenX_Datasheet_9w Surface downlight.pdf' },
  { name: 'ALU Bulkhead', href: '/datasheets/LumenX_Datasheet_ALU BLUKHEAD.pdf' },
  { name: 'Aegeon Downlight', href: '/datasheets/LumenX_Datasheet_Aegeon Downlight.pdf' },
  { name: 'COB Strip', href: '/datasheets/LumenX_Datasheet_COB STRIP.pdf' },
  { name: 'High Voltage Strip', href: '/datasheets/LumenX_Datasheet_High Voltage Strip.pdf' },
  { name: 'LF55x80 Linear Fitting', href: '/datasheets/LumenX_Datasheet_LF55x80.pdf' },
  { name: 'Linear 50x83mm', href: '/datasheets/LumenX_Datasheet_Linear 50x83mm.pdf' },
  { name: 'Linear 50x83mm 30W/m', href: '/datasheets/LumenX_Datasheet_Linear 50x83mm 30W:m.pdf' },
  { name: 'PC Bulkhead', href: '/datasheets/LumenX_Datasheet_PC BLUKHEAD.pdf' },
  { name: 'Performance Floods', href: '/datasheets/LumenX_Datasheet_Performance Floods.pdf' },
  { name: 'Recessed Panel 600x600', href: '/datasheets/LumenX_Datasheet_Recessed Panel.pdf' },
  { name: 'Saxa Triproof', href: '/datasheets/LumenX_Datasheet_Saxa Triproof.pdf' },
  { name: 'Thermisto Linear Highbay', href: '/datasheets/LumenX_Datasheet_Thermisto.pdf' },
  { name: 'V200 UFO Highbay', href: '/datasheets/LumenX_Datasheet_V200 Highbay.pdf' },
].sort((a, b) => a.name.localeCompare(b.name));
